### ISSUE TITLE
Dots/Slashes Appear on Buttons After Click

### ISSUE THREAD

**Issue by bskora** [kivymd/KivyMD#1019]
### Description of the Bug

Whenever I click a button, regardless of what type of button it is, a small slash/dot appears on the button. This isn't noticeable if you only press it once and go to another screen. However, it is once you return to the screen via another button. Also if you click and drag of the button, the dot/slash stays as well.

### Code and Logs

Kivy
```

            MDFillRoundFlatButton:
                #button has weird bug
                md_bg_color: app.theme_cls.primary_dark
                text: "New Game"
                font_style: "Button"
                size_hint: 0.99, 0.4
                pos_hint: {"center_x":0.5, "center_y":0.5}
                on_release:
                    app.root.current = "player"
                    app.root.transition.direction = "left"

```

### Screenshots

https://imgur.com/q45MZsj

### Versions

* OS: Windows 10
* Python: 3.9.4
* Kivy: 2.0.0
* KivyMD: 0.104.2
