### ISSUE TITLE
Issue in MDIconButton 

### ISSUE THREAD

**Issue by AnEx07** [kivymd/KivyMD#1081]
in android MDIconButton.set_size calculating bg size is too big 

i fix it with 
`
  def set_size(self, interval):
      print("here...")
      self.width = (
          "48sp" if not self.user_font_size else self.user_font_size + sp(25)
      )
      self.height = (
          "48sp" if not self.user_font_size else self.user_font_size + sp(25)
      )
`

**Comment by HeaTTheatR** [comment]
@AnEx07 
Please edit the example code and attach screenshots that show the icon size before and after your changes...

**Comment by AnEx07** [comment]
![Screenshot from 2021-09-13 21-31-05](https://user-images.githubusercontent.com/79507388/133118340-0656c49e-2db8-4238-867e-33cdda8772cd.png)
output in desktop
![Screenshot_2021-09-13-21-35-58-928_anex pack test_app](https://user-images.githubusercontent.com/79507388/133118549-35c4f01e-6a4b-43ee-bff3-4d467de75c69.jpg)
output in android


        
        __version__ = "0.0.1"
        
        from kivy.lang import Builder
        
        from kivymd.app import MDApp
        from kivymd.uix.button import MDIconButton
        from kivy.metrics import sp
        
        
        KV = '''
        MDScreen:
        
            MDIconButton:
                icon: "language-python"
                pos_hint: {"center_x": .5, "center_y": .75}
                md_bg_color: [1,0,0,1]
                user_font_size: "30sp"
                
        
            NewMDIconButton:
                icon: "language-python"
                pos_hint: {"center_x": .5, "center_y": .35}
                md_bg_color: [1,0,0,1]
                user_font_size: "30sp"
        
            
        '''
        
        class NewMDIconButton(MDIconButton):
            def set_size(self, interval):
                print("here...")
                self.width = (
                    "48sp" if not self.user_font_size else self.user_font_size + sp(25)
                )
                self.height = (
                    "48sp" if not self.user_font_size else self.user_font_size + sp(25)
                )
        
        
        
        
        class Example(MDApp):
            def build(self):
                return Builder.load_string(KV)
        
        
        Example().run()

**Comment by AnEx07** [comment]
and also my suggestion is to use sp as a default metrics it behave same almost same in android and desktop

**Comment by HeaTTheatR** [comment]
@AnEx07 I don't see any problem ...

**Comment by AnEx07** [comment]
the problem is the background size is too big for a given user_font_size in current MDIconButton as shown in upper icon button of  output on android screenshot but the background size in lower icon button is seems to be ok while user_font_size is same in both

**Comment by AnEx07** [comment]
here real issue i face...
![Screenshot from 2021-09-13 22-57-46](https://user-images.githubusercontent.com/79507388/133130063-1d1d85b9-4c64-4a1d-a878-a006f726318d.png)
output in desktop
![Screenshot from 2021-09-13 22-58-14](https://user-images.githubusercontent.com/79507388/133130116-730b11a0-0424-4f56-bb22-23bec3b1b483.png)
also output in desktop but similar ratio 
![Screenshot_2021-09-13-23-00-38-080_anex pack test_app](https://user-images.githubusercontent.com/79507388/133130341-a46d5a32-2608-4375-9099-c877235b0078.jpg)
output in android..

**Comment by HeaTTheatR** [comment]
@AnEx07 I don't see this behavior on mobile devices ...

**Comment by AnEx07** [comment]
[test_src.zip](https://github.com/kivymd/KivyMD/files/7156364/test_src.zip)
can you please execute this script

**Comment by HeaTTheatR** [comment]
@AnEx07 Please attach the minimal code that reproduces this behavior...

**Comment by AnEx07** [comment]
```
__version__ = "0.0.1"



from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.button import MDIconButton
from baseimport import *
from kivy.metrics import sp


KV = '''
MDScreen:
    MDIconButton:
        id: top1
        icon: "delete-sweep"
        pos_hint: {"center_x": 0.5,"center_y": 0.75}
        right: self.parent.right - sp(50)
        
        user_font_size: "25sp"
        mipmap: True
        md_bg_color: [0.8,0,0,0.5]

    MDIconButton:
        icon: "delete-sweep"
        x: top1.x-sp(30)
        y: top1.y-sp(30)

        right: self.parent.right - sp(50)
        
        user_font_size: "25sp"
        mipmap: True
        md_bg_color: [0.8,0,0,0.5]

    MDIconButton:
        icon: "delete-sweep"
        x: top1.x+sp(30)
        y: top1.y-sp(30)

        right: self.parent.right - sp(50)
        
        user_font_size: "25sp"
        mipmap: True
        md_bg_color: [0.8,0,0,0.5]
        
    NewMDIconButton:
        id: top2
        icon: "delete-sweep"
        pos_hint: {"center_x": 0.5,"center_y": 0.35}
        right: self.parent.right - sp(50)
        
        user_font_size: "25sp"
        mipmap: True
        md_bg_color: [0.8,0,0,0.5]

    NewMDIconButton:
        icon: "delete-sweep"
        x: top2.x-sp(30)
        y: top2.y-sp(30)

        right: self.parent.right - sp(50)
        
        user_font_size: "25sp"
        mipmap: True
        md_bg_color: [0.8,0,0,0.5]

    NewMDIconButton:
        icon: "delete-sweep"
        x: top2.x+sp(30)
        y: top2.y-sp(30)

        right: self.parent.right - sp(50)
        
        user_font_size: "25sp"
        mipmap: True
        md_bg_color: [0.8,0,0,0.5]
    


'''

class NewMDIconButton(MDIconButton):
    def set_size(self, interval):
        print("here...")
        self.width = (
            "48sp" if not self.user_font_size else self.user_font_size + sp(25)
        )
        self.height = (
            "48sp" if not self.user_font_size else self.user_font_size + sp(25)
        )




class Example(MDApp):
    def build(self):
        return Builder.load_string(KV)


Example().run()




```
