### ISSUE TITLE
Behavior change in MDDropdownMenu

### ISSUE THREAD

**Issue by Tyrn** [kivymd/KivyMD#1202]
### Description
After updating an old project after a couple of years, I got an error:
```
    TypeError: MDDropdownMenu.open() takes 1 positional argument but 2 were given
```
The relevant code (it used to work, two years ago), `main.py`:
```
        def build(self):
            ...
            return Builder.load_file("main.kv")
    
        def on_start(self):
            ...
            self.menu_lang_append()
        ...
        ...
    
        def menu_lang_append(self):
            self.menu_lang = MDDropdownMenu(width_mult=2)
            for lng in co_lang.LANG:
                self.menu_lang.items.append(
                    {
                        "viewclass": "MDMenuItem",
                        "text": lng,
                        "callback": self.menu_lang_callback,
                    }
                )
```
`main.kv`:
```
    MDBottomAppBar:
        MDToolbar:
            id: ps_toolbar
            title: T["co-toolbar-title"]
            icon: ACTION_ICON
            type: "bottom"
            animate_action_button: False
            next_icon: app.pulse_icon_counter() # Not a callback.
            on_action_button: app.discovery_request()
            right_action_items: [ ['minus-box-outline', lambda x: app.discovery_clean()], ['earth-box', lambda x: app.menu_lang.open(x)], ['dots-vertical', lambda x: app.menu_main.open(x)], ]
```
A very similar case [here](https://stackoverflow.com/questions/68588651/dropdown-menu-kivymd-not-opening), unresolved.

I tried to add the `caller` like this, no luck and no wonder; runtime errors

`main.py`:
```
        self.menu_lang = MDDropdownMenu(width_mult=2, caller=self.root.ids.ps_toolbar)
```
or
```
        self.menu_lang = MDDropdownMenu(width_mult=2, caller=self.root.ids.ps_toolbar.right_action_items)
```
`main.kv`:
```
        right_action_items: [... , ['earth-box', lambda x: app.menu_lang.open()], ...]
```
Software:
```
    [tool.poetry.dependencies]
    python = "^3.10"
    Kivy = "^2.1.0"
    kivymd = "^0.104.2"
```
It may not be a bug, strictly speaking. Unfortunately, on *stackoverflow* nobody seems to be interested; alternatively, somehow I can't pass the captcha on *Discord*.
