### ISSUE TITLE
Adding dynamic swiper item not working

### ISSUE THREAD

**Issue by nikolas-dev** [kivymd/KivyMD#1283]
Below is my code snippet. It shows an error Exception: ScrollView accept only one widget

HomePage.py

```
def list_stories(self):
    with open('assets/data/stories.json') as f_obj:
        data = json.load(f_obj)
        for name in data:
            self.ids.stories.add_widget(SwiperImageItem(
                avatar=data[name]['avatar'],
                name=name
            ))
```

HomePage.kv

```
MDBoxLayout:
    orientation: 'vertical'

    # Appbar
    AppBar:

    MDBoxLayout:
        adaptive_height: True
        MDSwiper:
            id: stories
            size_hint_y: None
            height: 100
```
SwiperImageItem.kv

```
<SwiperImageItem@MDSwiperItem>
    FitImage:
        source: root.avatar
        radius: [53]
```
