### ISSUE TITLE
MDFloatingActionButtonSpeedDial does not work with MDNavigationRail

### ISSUE THREAD

**Issue by blurryrox** [kivymd/KivyMD#1317]
So i am trying to add a `MDFloatingActionButtonSpeedDial ` into a screen navigated through the `MDNavigationRail `items but it doesn't even show up. 

When i try removing the `MDNavigationRail ` part, the FAB shows up which i find weird, this may be a bug, or i am doing something wrong i am not sure. Here's my coede:

main.py:
```
from kivymd.app import MDApp
from kivy.uix.screenmanager import ScreenManager, Screen

class CfgScreen(Screen):    
    data = {
        "Add user": "account-plus-outline"
        }

    def __init__(self, **kwargs):
        super(CfgScreen, self).__init__(**kwargs)

class MainApp(MDApp):   

    def build(self):
        self.theme_cls.primary_palette = "Teal"
        sm = ScreenManager()
        sm.add_widget(CfgScreen(name="cfg"))

        return sm

if __name__=="__main__":
    MainApp().run()
```

main.kv
```
CfgScreen:

<CfgScreen>:
    name: "cfg"
    BoxLayout:
        orientation: "horizontal"
        MDNavigationRail:
            md_bg_color: app.theme_cls.primary_color
            MDNavigationRailItem:
                id: navigation_rail
                icon: "account-details-outline"
        ScreenManager:
            id: sm_cfg
            Screen:
                name: "cfg_user_account"
                MDFloatingActionButtonSpeedDial:
                    data: root.data
                    root_button_anim: True
```
### Screenshots
With `MDNavigationRail`:
![wnav](https://user-images.githubusercontent.com/24860692/186474519-b31f3069-4271-45b1-8523-f993b1eb15dc.png)

Without the `MDNavigationRail` part:
![wonav](https://user-images.githubusercontent.com/24860692/186474641-8b4a1593-9bea-499f-85af-390c9173f074.png)

### Versions

* OS:  Windows 10
* Python:  3.10.6
* Kivy: 2.1.0
* KivyMD:  1.0.2
