### ISSUE TITLE
Elevation shade detaches with 2 x bottomNav items

### ISSUE THREAD

**Issue by LazzaAU** [kivymd/KivyMD#1420]
Issue :

With  at least 2 screens in a MDBottomNavigation + ScrollView + a widget that elevates such as a MDCard, the shade under the MDCard detaches from the widget if you switch tabs then back again. Result is when you scroll the shade stays put  while the rest of the screen scrolls. If you dont change screens, the elevation shade seems to stay attached to the widget as expected

Please feel free to close this if its also related to #1352 or similar

Below is minimal code to reproduce the issue. Which is basically two BottomNavigation screens  with a few widgets in it so that scrolling is achievable to highlight the issue.

To reproduce.
1) Copy below code and run it
2) switch to the "view profile tab"
3) switch back to the settings tab and then scroll the screen. You will notice the shading overlap the widgets and not scroll with the MDCard

For some reason i was un able to take a video or screenshot, but if you get the same results its pretty noticeable

Minimal
-------
```
from kivy.lang import Builder
from kivy.uix.screenmanager import Screen
from kivymd.app import MDApp

Builder.load_string('''
<InfoLabel@MDLabel>:
    font_size: dp(20)
    size_hint_y: None
    text_size: self.width, None
    valign: "center"
    height: self.texture_size[1]
    theme_text_color: "Custom"
    #text_color: app.theme_cls.primary_dark
    text_color: app.theme_cls.accent_color
    
<StandardLabel@MDLabel>:
    font_size: dp(18)
    size_hint_y: None
    text_size: self.width, None
    valign: "center"
    height: self.texture_size[1]
    opposite_colors: True
    #theme_text_color: "Custom"
    #text_color: "white"


<RedButton@MDRoundFlatButton>:
    opposite_colors: True
    font_size: dp(17)
    text_size: self.size
    line_width: 1.7
    halign: "center"
    valign: "center"
    size_hint_y: None
    height: dp(40)
    opacity: 1
    line_color: app.theme_cls.error_color
    text_color: "white"

<PrimaryButton@MDRoundFlatButton>:
    opposite_colors: True
    font_size: dp(17)
    text_size: self.size
    line_width: 1.7
    halign: "center"
    valign: "center"
    size_hint_y: None
    height: dp(40)
    opacity: 1
    line_color: app.theme_cls.primary_dark
    text_color: app.theme_cls.accent_color




<StandardCard@MDCard>:
    size_hint_x: .8
    size_hint_y: None
    height: self.minimum_height
    
    padding: dp(10),dp(25)
    halign: "center"
    focus_behavior: True
    md_bg_color: "darkgrey"
    unfocus_color: "darkgrey"
    focus_color: "grey"
    elevation: 6
    shadow_offset: -8, 8
    shadow_color: 0, 0, 0, .4
    shadow_softness: 12
    shadow_softness_size: 3.5
    
<MainScreen>:
    
    MDScreenManager:

        MDScreen:

            MDBoxLayout:
                orientation: 'vertical'
                

                MDGridLayout:
                    cols: 1

                    # Add a bottom Navigation bar
                    MDBottomNavigation:
                        #panel_color: app.theme_cls.accent_color
                        #selected_color_background: "orange"
                        text_color_active: "blue"
                        icon_active_color: "green"

                        MDBottomNavigationItem:
                            id: settings
                            name: 'settings'
                            text: 'Settings'
                            icon: 'cog'
                                                    

                            
                            ScrollView:
                                bar_width: 10
                                bar_color: app.theme_cls.accent_color
                                orientation: 'vertical'
                                scroll_type: ['bars', 'content']

                                MDGridLayout:
                                    cols: 1
                                    
                                    size_hint_y: None
                                    height: self.minimum_height
                                    spacing: dp(10),dp(20)
                                    padding: dp(10),dp(25)
                                    halign: "center"



                                    Image:
                                        source: 'Images/peeking-male.png'
                                        size_hint_y: None
                                        keep_ratio: True
                                        size_hint_x: .1


                                    StandardLabel:
                                        text: "Im Random text to fill up space"
                                        font_size: dp(20)
                                        halign: "center"
                                        theme_text_color: "Custom"
                                        text_color: 0, 1, 0, 1

                                    StandardCard:

                                        MDGridLayout:
                                            cols:1
                                            size_hint_y: None
                                            height: self.minimum_height
                                            spacing: dp(10),dp(20)
                                            padding: dp(10),dp(25)
                                            halign: "center"

                                            PrimaryButton:
                                                text: "Im Random text to fill up space"
                                                

                                            RedButton:
                                                text: "Im Random text to fill up space"
                                                

                                            InfoLabel:
                                                text: "Im Random text to fill up space"
                                                halign: "left"
                                           
                                            MDSeparator:
                                                height: dp(10)
                                                color: 0,0,0,0

                                            StandardLabel:
                                                text: "Im Random text to fill up space"


                                            PrimaryButton:
                                                text: "Im Random text to fill up space"

                                            RedButton:
                                                text: "Im Random text to fill up space"

                                            InfoLabel:
                                                text: "Im Random text to fill up space"

                                            MDSeparator:
                                                height: dp(20)
                                                color: 0,0,0,0

                                            StandardLabel:
                                                text: "Im Random text to fill up space"


                                    MDSeparator:
                                        height: dp(10)
                                        color: 0,0,0,0

                                    FitImage:
                                        source: 'Images/config.png'
                                        size_hint_y: None
                                        keep_ratio: True

                                    StandardCard:
                                        MDGridLayout:
                                            cols: 2
                                            size_hint_y: None
                                            padding: dp(10), dp(20)
                                            spacing: dp(10), dp(25)
                                            height: self.minimum_height

                                            InfoLabel:
                                                text: "Im Random text to fill up space"
                                                halign: "left"

                                            PrimaryButton:
                                                text: "Im Random text to fill up space"

                                            InfoLabel:
                                                text: "Im Random text to fill up space"
                                                halign: "left"

                                            MDTextField:
                                                text: "Im Random text to fill up space"

                                            InfoLabel:
                                                text: "Im Random text to fill up space"
                                                halign: "left"

                                            MDSwitch:
                                                id: notifications_on

                                            InfoLabel:
                                                text: "Im Random text to fill up space"
                                                halign: "left"

                                            MDTextField:
                                                text: "Im Random text to fill up space"
                                          

                                            InfoLabel:
                                                text: "Im Random text to fill up space"
                                                halign: "left"

                                            MDTextField:
                                                text: "Im Random text to fill up space"

                                            Image:
                                                source: 'Images/image.gif'
                                                size_hint_y: None
                                                keep_ratio: True
                                                size_hint_x: .7

                                    GridLayout:
                                        cols: 2
                                        size_hint_y: None
                                        padding: dp(10), dp(10)
                                        spacing: dp(10), dp(15)
                                        height: self.minimum_height

                                        MDFillRoundFlatButton:
                                            text: "Save"
                                            md_bg_color: "green"
                                            text_color: "white"
                                            line_color: "green"
                        
                        MDBottomNavigationItem:
                            id: view_profile
                            name: 'view_profile'
                            text: 'View Profile'
                            icon: 'face-man-profile'
                            

                            ScrollView:
                                bar_width: 5
                                orientation: 'vertical'
                                scroll_type: ['bars', 'content']

                                MDGridLayout:
                                    cols: 1
                                    # adding the next two lines makes the scrollVeiw scroll the contents
                                    size_hint_y: None
                                    height: self.minimum_height
                                    spacing: dp(10), dp(20)
                                    padding: dp(10), dp(25)
                                    halign: "center"

                                    StandardLabel:
                                        text: "Im random text"

                                    MDSeparator
                                        height: dp(10)
                                        color: 0,0,0,0



                                        
''')


class MainScreen(Screen):

    pass



class mainApp(MDApp):

    def build(self):
        self.theme_cls.theme_style = "Light"
        self.theme_cls.primary_palette = "Teal"
        self.theme_cls.accent_palette = "LightBlue"
        return MainScreen()

if __name__ == "__main__":
    test_app = mainApp()
    test_app.run()
```

### Versions

* OS: Linux
* Python: 3.9
* Kivy: 2.1.0
* KivyMD: 1.1.1
