### ISSUE TITLE
Error in MdSlider

### ISSUE THREAD

**Issue by FranciscoCarbonell** [kivymd/KivyMD#143]
#### Description of the Bug

Bug in MDSlider

### Code and Logs

```
BoxLayout:
    MDSlider:
```

`kivy.factory.FactoryException: Unknown class <Thumb>`

inside of slider.py

```
Thumb:
        id: thumb
        size_hint: None, None
        size:
            (dp(12), dp(12)) if root.disabled else ((dp(24), dp(24))\
            if root.active else (dp(16), dp(16)))
        pos:
            (slider.value_pos[0] - dp(8), slider.center_y - thumb.height/2 - dp(2))\
            if slider.orientation == 'horizontal'\
            else (slider.center_x - thumb.width / 2 - dp(2),\
            slider.value_pos[1] - dp(8))
        color:
            [0, 0, 0, 0] if slider._is_off else (root._track_color_disabled\
            if root.disabled else root.thumb_color_down)
        elevation:
            0 if slider._is_off else (4 if root.active else 2)
```

### Versions

* OS:  Windows 10
* Python: 3.7
* Kivy: 1.11.1
* KivyMD:

**Comment by HeaTTheatR** [comment]
There is no mistake!

**Comment by HeaTTheatR** [comment]
See `uix/slider.py`

**Comment by ArtemSBulgakov** [comment]
@FranciscoCarbonell Try to load your kv code inside build function

**Comment by HeaTTheatR** [comment]
Where did you find the mistake here?
![Снимок экрана 2019-11-15 в 20 56 19](https://user-images.githubusercontent.com/16930280/68964351-328c0400-07ea-11ea-86ab-97ece5570563.png)

**Comment by ArtemSBulgakov** [comment]
@HeaTTheatR Why do you close issue??? Why do you think that this is not a bug? You even didn't see code where bug is reproducedable!

**Comment by HeaTTheatR** [comment]
@Mountaino  Provide a more detailed description of the problem, more if you think this is a mistake in the library.

**Comment by HeaTTheatR** [comment]
The error does not play on my computer. There is no detailed description of the problem in the question ...

**Comment by ArtemSBulgakov** [comment]
@HeaTTheatR Before closing issue you need to ask details. Do not close issue if you don't understand why it did happen on @FranciscoCarbonell computer.

**Comment by HeaTTheatR** [comment]
I don’t want the “empty” questions hanging in the air ... As soon as you can see the real code that reproduces the error, the question can be opened.

**Comment by FranciscoCarbonell** [comment]
I execute the slide.py file, where the following code is executed

```
if __name__ == "__main__":
    from kivy.app import App
    from kivymd.theming import ThemeManager

    class SliderApp(App):
        theme_cls = ThemeManager()

        def build(self):
            return Builder.load_string(
                """
BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        size_hint_y: None
        height: '48dp'
        Label:
            text: "Toggle disabled"
            color: [0, 0, 0, 1]
        CheckBox:
            on_press: slider.disabled = not slider.disabled
    BoxLayout:
        size_hint_y: None
        height: '48dp'
        Label:
            text: "Toggle active"
            color: [0, 0, 0, 1]
        CheckBox:
            on_press: slider.active = not slider.active
    BoxLayout:
        size_hint_y: None
        height: '48dp'
        Label:
            text: "Toggle show off"
            color: [0, 0, 0, 1]
        CheckBox:
            on_press: slider.show_off = not slider.show_off

    MDSlider:
        id: slider
        min: 0
        max: 100
        value: 40

    MDSlider:
        id: slider2
        orientation: "vertical"
        min: 0
        max: 100
        value: 40

"""
            )

    SliderApp().run()
```

`python slide.py`

output: `kivy.factory.FactoryException: Unknown class <Thumb>`

and other example

**main.py**

```
from kivy.app import App
from kivymd.theming import ThemeManager

class Main(App):
    theme_cls = ThemeManager()

Main().run()
```

**main.kv**

```
NavigationLayout:
    MDNavigationDrawer:
        drawer_logo: "menu.png"

        NavigationDrawerIconButton:
            icon: "home"
            text: "Inicio"
            on_release: screen_manager.current = "screen_inicio"

        NavigationDrawerIconButton:
            icon: "lock"
            text: "Pagina segunda"
            on_release: screen_manager.current = "screen_segundo"


    BoxLayout:
        orientation: "vertical"
        MDToolbar:
            title: "Aplicacion de ejemplo"
            md_bg_color: app.theme_cls.primary_color
            left_action_items: [["menu", lambda x: app.root.toggle_nav_drawer()]]

        ScreenManager:
            id: screen_manager

            Screen:
                name: "screen_inicio"

                BoxLayout:
                    orientation: "vertical"
                    MDSlider:
                        id:slider
                        min:0
                        max:100
                        value: 40
                    MDLabel:
                        text: "Pagina Inicio"
                    MDProgressBar:
                        value: 10
            Screen:
                name: "screen_segundo"
                MDLabel:
                    text: "Pagina segunda"
```
