### ISSUE TITLE
StencilBehavior does not behave as expected with RelativeLayout

### ISSUE THREAD

**Issue by woxy005** [kivymd/KivyMD#1452]
If you modified it
from
```
StencilPush
RoundedRectangle:
    pos: root.pos
    size: root.size
```
to 
```
StencilPush
RoundedRectangle:
    pos: root.to_local(*root.pos)
    size: root.size
```
, it works as expected.
