### ISSUE TITLE
Im getting error AttributeError: 'super' object has no attribute '__getattr__'

### ISSUE THREAD

**Issue by furjac** [kivymd/KivyMD#1462]
### Description of the Bug

this is the full traceback 
```   File "kivy\_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
   File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1191, in kivy._event.EventObservers._dispatch
   File "C:\Users\Furjack\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\lang\builder.py", line 55, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "C:\Users\Furjack\Documents\elpatron\speech.kv", line 42, in <module>
     on_release: app.screenrecord()
   File "c:\Users\Furjack\Documents\elpatron\Main.py", line 33, in screenrecord
     min = time.time()+60*eval(self.root.ids.screenrecordmin.text)
   File "kivy\properties.pyx", line 964, in kivy.properties.ObservableDict.__getattr__
 AttributeError: 'super' object has no attribute '__getattr__'
```

### Code and Logs

these are the codes
main.py

```
from kivymd.app import MDApp
from kivy.lang import Builder
from win32api import GetSystemMetrics
from kivy.uix.screenmanager import ScreenManager, Screen
import time
from PIL import ImageGrab
import cv2
import numpy as ny
from kivy.properties import ObjectProperty


class TestApp(MDApp):
    global sm

    screenrecordmin = ObjectProperty(None)
    screenrecordname = ObjectProperty(None)

    sm = ScreenManager()

    def build(self):

        # Create the screen manager
        sm.add_widget(Builder.load_file('main_page.kv'))
        sm.add_widget(Builder.load_file('speech.kv'))
        # sm.add_widget(Builder.load_file('sign.kv'))
        return sm

    def change_to_speech(self):
        sm.current = "Speech"

    def screenrecord(self):
        # self.root.get_running_app().root_window.minimize()
        min = time.time()+60*eval(self.root.ids.screenrecordmin.text)
        height = GetSystemMetrics(1)
        width = GetSystemMetrics(0)

        file_name = f'{self.root.ids.screenrecordname.text}.mp4'
        format = cv2.VideoWriter_fourcc('m', 'p', '4', 'v')
        final_video = cv2.VideoWriter(file_name, format, 20.0, (width, height))

        while time.time() < min:
            img = ImageGrab.grab(bbox=(0, 0, width, height))
            img_ny = ny.array(img)
            final_image = cv2.cvtColor(img_ny, cv2.COLOR_BGR2RGB)
            final_video.write(final_image)


if __name__ == '__main__':
    TestApp().run()
```

speech.kv

```
MDScreen:
    name: "Speech"
    FloatLayout:
        orientation:'vertical'
        pos: self.pos
        size: root.size   

        MDLabel:
            text: 'Welcome to screen recorder app'
            pos_hint:{'center_x':0.5,'center_y':0.905}
            font_size: (self.height/15)* 0.75

        MDLabel:
            text: 'Press the screen record button to screen record the screen'
            pos_hint:{'center_x':0.5,'center_y':0.705}
            font_size: (self.height/15)* 0.65

        MDLabel:
            text: 'Input the name of the file'
            pos_hint:{'center_x':0.3,'center_y':0.555}
            font_size: (self.height/15)* 0.65

        MDLabel:
            text: 'Input the number of minutes'
            pos_hint:{'center_x':0.3,'center_y':0.455}
            font_size: (self.height/15)* 0.65    

        TextInput:
            id: screenrecordname
            size_hint: 0.2, 0.05    
            pos_hint:{'center_x':0.6,'center_y':0.555}

        TextInput:
            id: screenrecordmin
            size_hint: 0.2, 0.05    
            pos_hint:{'center_x':0.62,'center_y':0.455}

        Button:
            text:'Screen Record'
            size_hint: .3,.1
            pos_hint:{'center_x':0.47,'center_y':0.354}    
            on_release: app.screenrecord()
```
main_page.kv
```
MDScreen:
    name: "Main_screen"
    MDBoxLayout:
        orientation: "vertical"
        MDLabel:
            text: 'Aidem - Integrated SLR Application'
            background_normal: ''
            background_color: (1, 1, 1, 1)
            text_color: "black"
            halign: "center"
        Button:
            text: 'Sign Language to Speech'
            background_normal: ''
            background_color: (0, 1, 0, 1) # Green color
            on_press: app.change_to_speech()
        Button:
            text: 'Speech to Sign Language'
            background_normal: ''
            background_color: (0, 0, 1, 1) # Blue color
            on_press: root.manager.current = 'speech'
```

please tell whats the problem of this app ,but when i print the self.root.ids it gives me empty {}

### Versions

* OS: windows 10
* Python: 3.9
* Kivy: 2.2.0
* KivyMD: 1.1.1

**Comment by FilipeMarch** [comment]
You don't understand how references work on Kivy. Here it is an example you should try yourself and try to understand it.

`main.py`
```python
from kivymd.app import MDApp
from kivymd.uix.screen import MDScreen
from kivy.lang import Builder
from kivy.uix.screenmanager import ScreenManager, Screen


class MainScreen(MDScreen):
    def print_references(self):
        print("\n\n")
        print("*** References from Main Screen ***")
        print("Main Screen is the root widget of the buttons")

        print("Getting button_one from Main Screen ids")
        print(self.ids.button_one)

        print("Getting button_two from Main Screen ids")
        print(self.ids.button_two)

        print("Getting button_two from Main Screen.button_two")
        print(self.button_two)

        print("Get button_two reference from app")
        app = MDApp.get_running_app()
        print(app.screen_manager.get_screen("Main Screen").button_two)


Builder.load_file("main_screen.kv")


class TestApp(MDApp):
    def build(self):
        self.screen_manager = ScreenManager()
        self.main_screen = MainScreen()
        self.screen_manager.add_widget(self.main_screen)
        return self.screen_manager

    def print_references(self):
        print("\n")
        print("*** References from App ***")
        print("Getting main screen from self")
        print(self.main_screen)

        print("Getting main screen from screen manager")
        print(self.screen_manager.get_screen("Main Screen"))

        print("Getting button_one from Main Screen ids")
        print(self.main_screen.ids.button_one)

        print("Getting button_two from Main Screen ids")
        print(self.main_screen.ids.button_two)

        print("Getting button_two from Main Screen.button_two")
        print(self.main_screen.button_two)


if __name__ == "__main__":
    TestApp().run()
```

`main_screen.kv`
```yml
<MainScreen>:
    name: "Main Screen"
    button_two: button_two
    BoxLayout:
        Button:
            id: button_one
            text: "Print references from root"
            on_release: root.print_references()
        Button:
            id: button_two
            text: "Print references from app"
            on_release: app.print_references()
```
