### ISSUE TITLE
MDNavigationDrawer Question / Clarification

### ISSUE THREAD

**Issue by vitormhenrique** [kivymd/KivyMD#151]
#### Description of the Bug

Hello everyone, I'm trying to build a simple app with the MDNavigationDrawer, according to the documentation, it says that the structure should be:

```
Root:
    NavigationLayout:
        ScreenManager:
            ...
            ...
        MDNavigationDrawer:
            UserContentNavigationDrawer:
```

But compiling the example bellow gives me a weird behavior: 
![](https://i.ibb.co/3FyJr0S/Screen-Shot-2019-12-25-at-1-36-30-PM.png)

I also noticed that the kitchen sink project uses a different structure layout:

```
NavigationLayout
    MDNavigationDrawer
        FloatLayout
            BoxLayout
                ScreenManager
```

I'm a little confused on how to use the Screenmanager and the MDNavigationDrawer

My ultimate goal was to convert a Kivy app that I already have to use kivymd.

A very stripped down version of my app is the following:

on main.py

```
from kivy.lang import Builder
from kivy.uix.screenmanager import ScreenManager
from home import HomeScreen

Builder.load_file('home.kv')

sm = ScreenManager()
sm.add_widget(HomeScreen(name='home'))

class Bconfig(App):
    def build(self):
        return sm

Bconfig().run()
```

on home.kv:

```
#:kivy 1.0
<HomeScreen>:
    BoxLayout:
        orientation: 'vertical'
        FloatLayout:
            canvas:
                Color:
                    rgb: 1, 1, 1
                Rectangle:
                    source: 'background.png'
                    size: self.size
            AnchorLayout:
                anchor_y: "center"
                GridLayout:
                    cols: 1
                    size_hint: None, None
                    height: self.minimum_height
                    width: self.minimum_width
                    spacing: dp(10)
                    Button:
                        size_hint: None, None
                        size: dp(150), dp(50)
                        text: 'Hello World'
```

and finally on home.py:
```
import kivy
from kivy.uix.screenmanager import Screen

class HomeScreen(Screen):
    pass
```

of course I do add many more screens on the screen manager and I build my app that way.

### Versions

* OS: macOS Catalina 10.15.2 (19C57)
* Python: Python 3.7
* Kivy: 1.11.1
* KivyMD: 0.102.1
