### ISSUE TITLE
hint text not working with multiline

### ISSUE THREAD

**Issue by stekeltje28** [kivymd/KivyMD#1607]
### Description of the Bug

hint text isnt working when multiline = True

when using multiline there is no HintText, when I select the textfield the HintText appears but as soon as I have typed one or more enters the HintText appears in the middle

I'm getting this problem with version 2.0.1dev0
### Code and Logs

```python
from kivy.lang import Builder
from kivymd.app import MDApp

KV = '''
BoxLayout:
    orientation: 'vertical'
    MDTextField:
        id: textfield
        multiline: True
        MDTextFieldHintText:
            text: "HintText"
'''

class MyApp(MDApp):
    def build(self):
        return Builder.load_string(KV)

if __name__ == '__main__':
    MyApp().run()

```

### Versions

* OS: 
* Python: 
* Kivy: 
* KivyMD:

**Comment by HeaTTheatR** [comment]
Please, describe the problems in more detail.

**Comment by KoJIbaca** [comment]
I think he meant it.

![image](https://github.com/kivymd/KivyMD/assets/62202187/b821dfd2-a207-4ed8-af9b-17c41f691596)

My code for this widget:

```
        MDTextField:
            id: feedback_text
            mode: "outlined"
            multiline: True
            size_hint: .8, .3
            pos_hint: {'center_x': .5, 'center_y': .24}
            MDTextFieldHintText:
                text: 'Краткое описание проблемы'
```

I would like to note that there are attempts to fix the size of the field, but nothing helps
