### ISSUE TITLE
Navigation drawer and search bar overlapping issue

### ISSUE THREAD

**Issue by navjotcis** [kivymd/KivyMD#163]
In my case when I am implementing common header like this 
```
NavigationLayout:

    MDToolbar:
        id: toolbar
        pos_hint: {"top": 1}
        title: "Navigation Drawer"
        md_bg_color: app.theme_cls.primary_color
        elevation: 10
        left_action_items: [['menu', lambda x: nav_drawer.toggle_nav_drawer()]]

    ScreenManager:
        id: scr_mngr
        size_hint_y: None
        height: root.height - toolbar.height

        Test1:
            id:sc1
        Test2:
            id:sc2
        Test3:
            id:sc3

    MDNavigationDrawer:
        id: nav_drawer

        ContentNavigationDrawer:
            id: content_drawer
```
for multiple screens and if I am implementing search bar on it then both are overlapping but
in older versions, I am not facing overlapping issues. see below how problem looks like
