### ISSUE TITLE
Invalidation of attributes when creating dynamic classes using kvlang in kivymd

### ISSUE THREAD

**Issue by WangZhongDian** [kivymd/KivyMD#1704]
```
#:kivy 2.3.0
#:import NoTransition kivy.uix.screenmanager.NoTransition

<MiddleTopAppBar@MDTopAppBar>:
    

<MiddleTopAppBarTitle@MDTopAppBarTitle>:
    role:'small'
    type: 'small'
    pos_hint: {'center_x': 0.5}

<MiddleSM>:
    transition: NoTransition()
    MDScreen:
        name: 'taskpage'
        MDBoxLayout:
            orientation: 'vertical'
            MiddleTopAppBar:
                size_hint_y: 0.08
                MDTopAppBarLeadingButtonContainer:
                    MDActionTopAppBarButton:
                        icon: ''
                MiddleTopAppBarTitle:
                    text: '待办'
                    role:'small'
                MDTopAppBarTrailingButtonContainer:
                    MDActionTopAppBarButton:
                        icon: "plus"
                        on_release: root.add_team()
            ScrollView:
                pos_hint: {'center_x': 0.5, 'center_y': 0.5}
                do_scroll_x: False
                effect_cls: 'OpacityScrollEffect'
                MDGridLayout:
                    spacing: 2
                    id:scroll_grid_layout
                    cols: 1
                    adaptive_height: True
```
Many attributes such as role cannot take effect
