### ISSUE TITLE
MDNavigationDrawerLabel won't let me control the text within its bounding box

### ISSUE THREAD

**Issue by mz3r0** [kivymd/KivyMD#1736]
I have it inside an MDNavigationDrawerMenu

```
MDNavigationDrawerLabel:
    text: "My Text"
    font_style: "Headline"
    halign: "center"
    d: self.show_area('g', group='after')
```

The problem: I noticed plenty of space under the text.

I thought it was padding at first, then line height. Tried messing around with different things but nothing seemed to work. The headline `font_style` looks great but the extra space added underneath is out of my control which makes me not want to use it.

OS: Windows 10
Python: 3.12
Kivy: 2.3.0
KivyMD: 2.0.1.dev0
