### ISSUE TITLE
MDNavigationDrawer BUG Always Closed when scrolling

### ISSUE THREAD

**Issue by JuditNugroho** [kivymd/KivyMD#175]
Hello all, i am new in develop kivymd. i wont to ask something
First sorry to my bad english.
I was develop new program and using navigation drawer in kivymd when i running on text editor this drawer is good but after i deploy in buildozer and exe this drawer always close when i scrolling down and top. 
How can i solve this?
Thanks for your attention
(By the way sorry for i cant to take screenshot because that is secret company)

**Comment by HeaTTheatR** [comment]
@JuditNugroho Make a minimal example that reproduces your problem. Then you can show us this error.

**Comment by JuditNugroho** [comment]
![image](https://user-images.githubusercontent.com/47251536/73590488-94205c80-4515-11ea-8326-c5266109be64.png)
![image](https://user-images.githubusercontent.com/47251536/73590489-984c7a00-4515-11ea-80c0-bb5230d5fac9.png)
i am using MDExpansionPanel too for this navigation drawer 
        for a in list:
            if a == 'A':
                self.ids.menu_list.add_widget(
                    MDExpansionPanel(content=contentMenuMaster, icon='assets/data.png', title=a))
            elif a == "B":
                self.ids.menu_list.add_widget(
                    MDExpansionPanel(content=contentMenuProses, icon='assets/proses.png', title=a))
            elif a == "C":
                self.ids.menu_list.add_widget(
                    MDExpansionPanel(content=contentMenuTransaction, icon='assets/transaksi.png', title=a))
            elif a == "D":
                self.ids.menu_list.add_widget(
                    MDExpansionPanel(content=contentMenuReport, icon='assets/laporan.png', title=a))

**Comment by JuditNugroho** [comment]
First,sorry. Can i have the sub menu like accordion or dropdown in navigation drawer? If yes how can i do?

**Comment by HeaTTheatR** [comment]
@JuditNugroho The minimum example that can be run.

**Comment by JuditNugroho** [comment]
Sorry for not understanding your answer 
this minimum example that can be run
```
from kivy.uix.boxlayout import BoxLayout

from kivymd.app import MDApp
from kivy.lang import Builder
from kivy.properties import StringProperty
from kivymd.uix.expansionpanel import MDExpansionPanel
from kivymd.uix.list import OneLineAvatarListItem

KV = '''
#:import IconLeftWidget kivymd.uix.list.IconLeftWidget
#:import images_path kivymd.images_path


<NavigationItem>
    theme_text_color: 'Custom'
    divider: None

    IconLeftWidget:
        icon: root.icon

<ContentA>
    orientation: 'vertical'
    padding: dp(10)
    spacing: dp(10)
    size_hint_y: None
    height: self.minimum_height

    OneLineIconListItem:
        text: "A"

    OneLineIconListItem:
        text: "A"
        on_press: print("click")

    OneLineIconListItem:
        text: "A"
        on_press: print("click")
    OneLineIconListItem:
        text: "A"

    OneLineIconListItem:
        text: "A"
        on_press: print("click")

    OneLineIconListItem:
        text: "A"
        on_press: print("click")
    OneLineIconListItem:
        text: "A"

    OneLineIconListItem:
        text: "A"
        on_press: print("click")

    OneLineIconListItem:
        text: "A"
        on_press: print("click")
        
<ContentNavigationDrawer>

    BoxLayout:
        orientation: 'vertical'

        FloatLayout:
            size_hint_y: None
            height: "200dp"

            canvas:
                Color:
                    rgba: app.theme_cls.primary_color
                Rectangle:
                    pos: self.pos
                    size: self.size

            BoxLayout:
                id: top_box
                size_hint_y: None
                height: "200dp"
                #padding: "10dp"
                x: root.parent.x
                pos_hint: {"top": 1}

                FitImage:
                    source: f"{images_path}kivymd_alpha.png"

            MDIconButton:
                icon: "close"
                x: root.parent.x + dp(10)
                pos_hint: {"top": 1}
                on_release: root.parent.toggle_nav_drawer()

            MDLabel:
                markup: True
                text: "[b]KivyMD[/b]\\nVersion: 0.102.1"
                #pos_hint: {'center_y': .5}
                x: root.parent.x + dp(10)
                y: root.height - top_box.height + dp(10)
                size_hint_y: None
                height: self.texture_size[1]

        ScrollView:
            pos_hint: {"top": 1}

            GridLayout:
                id: box_item
                cols: 1
                size_hint_y: None
                height: self.minimum_height


Screen:

    NavigationLayout:

        ScreenManager:

            Screen:

                BoxLayout:
                    orientation: 'vertical'

                    MDToolbar:
                        title: "Navigation Drawer"
                        md_bg_color: app.theme_cls.primary_color
                        elevation: 10
                        left_action_items: [['menu', lambda x: nav_drawer.toggle_nav_drawer()]]

                    Widget:


        MDNavigationDrawer:
            id: nav_drawer

            ContentNavigationDrawer:
                id: content_drawer

'''


class ContentNavigationDrawer(BoxLayout):
    pass


class NavigationItem(OneLineAvatarListItem):
    icon = StringProperty()


class ContentA(BoxLayout):
    pass


class TestNavigationDrawer(MDApp):
    def build(self):
        return Builder.load_string(KV)

    def on_start(self):
        contentA = ContentA()
        lists = (
            'A', 'B', 'C', 'D'
        )
        for a in lists:
            self.root.ids.content_drawer.ids.box_item.add_widget(
                MDExpansionPanel(content=contentA, title=a, icon="data/logo/kivy-icon-128.png")
            )


TestNavigationDrawer().run()
```
thanks for your attention
