### ISSUE TITLE
Ripple effect not drawn correctly on moving button (using 'standard' NavigationDrawer)

### ISSUE THREAD

**Issue by LCUnger** [kivymd/KivyMD#1758]
### Description of the Bug

Disclaimer: I'm really new to KivyMD, and just finished one project in normal kivy.

When using a NavigationDrawer of type "standard". And a pos_hinted button in the screen accompanied by it. De ripple effect of the button doesn't move with the button. It presents itself either on the left or right depending on if you're opening or closing the Drawer. I tried to use 'ripple_effect: False', and '_no_ripple_effect: True'. But these don't turn of the ripple effect. 

### Code and Logs

The code is the same as the example from the documentation, except I changed the drawer_type to "standard".

```
from kivy.lang import Builder

from kivymd.app import MDApp

KV = '''
MDScreen:
    md_bg_color: self.theme_cls.backgroundColor

    MDNavigationLayout:

        MDScreenManager:

            MDScreen:

                MDButton:
                    pos_hint: {"center_x": .5, "center_y": .5}
                    on_release: nav_drawer.set_state("toggle")

                    MDButtonText:
                        text: "Open Drawer"

        MDNavigationDrawer:
            id: nav_drawer
            radius: 0, dp(16), dp(16), 0
            drawer_type: "standard"

            MDNavigationDrawerMenu:

                MDNavigationDrawerLabel:
                    text: "Mail"

                MDNavigationDrawerItem:

                    MDNavigationDrawerItemLeadingIcon:
                        icon: "account"

                    MDNavigationDrawerItemText:
                        text: "Inbox"

                    MDNavigationDrawerItemTrailingText:
                        text: "24"

                MDNavigationDrawerDivider:
'''


class Example(MDApp):
    def build(self):
        return Builder.load_string(KV)


Example().run()

```

### Screenshots

Used the best of my ability to screenshot during the action. 

![Image](https://github.com/user-attachments/assets/519ead7d-1729-41e9-82a8-2620f98e8bf2)

![Image](https://github.com/user-attachments/assets/83190a42-abbd-4123-b91f-65eab84c40e6)

### Versions

* OS: Windows 
* Python: 3.13.0
* Kivy: 2.3.1
* KivyMD:  2.0.1.dev0
