### ISSUE TITLE
Why FitImage inherit AsyncImage on FitImage? doesn't work well

### ISSUE THREAD

**Issue by ITSTIME1** [kivymd/KivyMD#1763]
### Description of the Bug

I face to seems like alpha channel missing or AsyncImage bug. When i running process (main.py) FitImage load image on screen but a flicker occurred in an instant. (detail description you should check below compare images)

### Code and Logs

```
class EConsentTabletView(MDScreen):

    class AppBarManipulation(EventDispatcher):
        page_text = StringProperty("1")


    class AppBarInformation(EventDispatcher):
        hospital_name = StringProperty("test hospital")
        user = StringProperty("test")
    
    

    def __init__(self, *args, **kwargs):
        
        self.app_bar_manipulation_layout = self.AppBarManipulation()
        self.app_bar_information_layout = self.AppBarInformation()
        super().__init__(*args, **kwargs)



    def on_leave(self):
        self.clear_data()
        Logger.info("Leave Tablet View Clear data...")

    def on_enter(self):
        self.load_data()
        Logger.info("Enter Tablet View Start Data loading...")

    def load_data(self):
        Logger.info("Data load & set")

    
    def clear_data(self):
        pass

class EConsentResponsiveView(MDResponsiveLayout, MDScreen):
    mobile_view = ObjectProperty(None)
    tablet_view = ObjectProperty(None)
    desktop_view = ObjectProperty(None)
    current_mode = None

    def __init__(self, **kw):
        super().__init__(**kw)
        self.screen_manager = ScreenManager()
        self.mobile_view = self.MobileView(name="mobile")
        self.tablet_view = EConsentTabletView(name="tablet")
        self.desktop_view = self.DesktopView(name="desktop")

        self.screen_manager.add_widget(self.mobile_view)
        self.screen_manager.add_widget(self.tablet_view)
        self.screen_manager.add_widget(self.desktop_view)

        self.add_widget(self.screen_manager)
        self.update_view()  
    
    def update_view(self):
        if self.width < 600:
            mode = "mobile"
            self.mobile_view.opacity = 1
            self.tablet_view.opacity = 0
            self.desktop_view.opacity = 0
            self.screen_manager.current = "mobile"  

        elif self.width < 1600:
            mode = "tablet"
            self.mobile_view.opacity = 0
            self.tablet_view.opacity = 1
            self.desktop_view.opacity = 0
            self.screen_manager.current = "tablet" 

        else:
            mode = "desktop"
            self.mobile_view.opacity = 0
            self.tablet_view.opacity = 0
            self.desktop_view.opacity = 1
            self.screen_manager.current = "desktop"  


        if mode != self.current_mode:
            self.current_mode = mode
            Logger.info(f"EConsentResponsiveView: Switched to {mode} view")

        Logger.info(f"width: {self.width}, height:{self.height}")



    def on_size(self, *args):
        self.update_view()

    def on_start(slef):
        pass

    def on_stop(self):
        pass

    class MobileView(MDScreen):
        pass

    class DesktopView(MDScreen):
        pass

class EConsentView(MDApp):
    def build(self):
        return Builder.load_file("design/econsent_responsive_view.kv")

if __name__ == "__main__":
    from kivy.core.window import Window
    from kivy.metrics import dp

    dp_width, dp_height = 1706.66, 1066.66
    Window.minimum_width = dp(dp_width) * 0.1
    Window.minimum_height = dp(dp_height) * 0.1
    
    EConsentView().run()
```

kv design file

```
MDFloatLayout:
                orientation: "vertical"
                size_hint_y: 0.9
                MDScrollView:
                    size_hint_y: 1 
                    bar_width: dp(8)
                    bar_color: 0, 0, 0, 0.26
                    bar_inactive_color: 0, 0, 0, 0.11  
                    FitImage:
                        source: 'assets/image/dummy.png'
                        fit_mode : "cover"
                        size_hint_y: None
                        height: dp(1000)  
```

### Screenshots
![Image](https://github.com/user-attachments/assets/3aa10b26-dd34-4fe6-9705-8d18b9250e61)

Add images to explain us this bug. Paste urls here.

Remove this section if no images here

### Versions

Python: 3.11.9
OS: Windows 10 Pro
Kivy: 2.3.1
KivyMD: 2.0.1.dev0
Kivy installation method: This way that archeive.zip download (pip install... ..zip)
