### ISSUE TITLE
MDDropdownMenu on_press event

### ISSUE THREAD

**Issue by yunus-ceyhan** [kivymd/KivyMD#19]
I want to call a function when o click on one of the MDDropdownMenu's item, but i dont know how?

Thats how i added MDDropdownMenu.
```
Toolbar:
    id: toolbar
    elevation: 9
    pos_hint: {'top':1}
    title: 'Test App'
    md_bg_color: [.2, .3, .5, 1]
    background_palette: 'Primary'
    background_hue: '700'
    right_action_items: [['dots-vertical', lambda x: MDDropdownMenu(items=app.menu_items, width_mult=4).open(self)]]


```

And  menu_items

```
    menu_items = [
        {'viewclass': 'MDMenuItem',
         'text': 'About'},]

```

lets say i have a fuction in main class
```
    def example(self,*args):
        pass
```

how can i call this with on_press event over one of the MDDropdownMenu item?
