### ISSUE TITLE
How can i change screens with popup widget and toolbar

### ISSUE THREAD

**Issue by akgupta0777** [kivymd/KivyMD#213]
### Help me change the screens of my app with toolbar
StartOptions is my Screen Name.I am just pasting the code of Toolbar
### Code and Logs

```python
MDToolbar:
        title: "16 Slips"
        right_action_items: [["eye", lambda x: root.sneak_peak()],["exit-to-app", lambda x:  
         app.root.current="StartOptions"]]
        specific_text_color: app.theme_cls.primary_color
        md_bg_color:[0,0,0,1]
        type:"top"  
        pos_hint:{"top":1} 
"""
Logs
File "<string>", line 451
     [["eye", lambda x: root.sneak_peak()],["exit-to-app", lambda x:app.root.transition = SlideTransition(direction = "left")  app.root.current="StartOptions"]]
                                                                                        ^
 SyntaxError: invalid syntax

### Versions

* OS:  Windows 10 Home 
* Python:  Python 3.7
* Kivy: Latest Version
* KivyMD:  Latest Version

**Comment by HeaTTheatR** [comment]
@akgupta0777 
```
MDToolbar:
    title: "16 Slips"
    right_action_items: [["eye", lambda x: root.sneak_peak()], ["exit-to-app", lambda x:  root.set_screen(app)]]
```

```python
def set_screen():
    instance_screen_manager.current = "StartOptions"
```

**Comment by ShubhamSolse** [comment]
def set_screen():
    instance_screen_manager.current = "StartOptions"

Unresolved reference 'instance_screen_manager'

**Comment by ShubhamSolse** [comment]
pls help

**Comment by kulothunganug** [comment]
@ShubhamSolse use
in .py
```py
from kivy.app import App

def set_screen(self):
    App.get_running_app().root.current = "StartOptions"
```
in kv
```yaml
MDToolbar:
        title: "16 Slips"
        right_action_items: [["eye", lambda x: root.sneak_peak()],["exit-to-app", lambda x: root.set_screen()]]
        specific_text_color: app.theme_cls.primary_color
        md_bg_color:[0,0,0,1]
        type:"top"  
        pos_hint:{"top":1} 
```
