### ISSUE TITLE
Dismissing a list item (to GC)

### ISSUE THREAD

**Issue by Tyrn** [kivymd/KivyMD#249]
List items apparently are not garbage collected.

Here is a Hello World like app with two buttons. The big one populates a list with 50 items, the little one clears it. Memory usage inspection I'm running like this:
```
$ mprof run --include-children python leak.py 
...
$ mprof plot --output out.png
```
The required software is `matplotlib` and `memory-profiler`. Whenever you run the test, creating and then clearing the list several times by clicking the buttons, you get a plot like a steadily ascending stairway. How am I supposed to convince Kivy(MD) to release the items no longer needed?

`leak.py`:
```
from functools import partial
import kivy

kivy.require("1.11.1")
from kivy.utils import platform

print(f"platform: {platform}")

from kivy.lang import Builder
from kivy.uix.floatlayout import FloatLayout

from kivymd.app import MDApp
from kivymd.uix.tab import MDTabsBase
from kivymd.uix.list import TwoLineAvatarIconListItem
import gc


ACTION_ICON = "eye"


class PowerListItem(TwoLineAvatarIconListItem):
    """The engaged power supply item."""


class TabList(FloatLayout, MDTabsBase):
    """The engaged power supplies tab."""

    def surfacing(self, tab_text):
        pass

    def discover(self, cnt):
        ids = MDApp.get_running_app().root.ids
        for i in range(cnt):
            item = PowerListItem(
                text="List Item" + f" {i + 1:>2}", secondary_text="none"
            )
            ids.ps_list.add_widget(item)


class Contero(MDApp):

    def build(self):
        return Builder.load_file("leak.kv")

    def on_start(self):
        self.theme_cls.primary_palette = "Gray"

    def discovery_clean(self):
        for item in self.root.ids.ps_list.children:
            print(f"item: {item.text}")
        self.root.ids.ps_list.clear_widgets()
        gc.collect()

    def discovery_request(self, item_count=50):
        self.discovery_clean()

        tab_list = self.root.ids.ps_tab_list

        tab_list.discover(item_count)

    def on_tab_switch(self, instance_tabs, instance_tab, instance_tab_label, tab_text):
        """Called when switching tabs.
        """

        instance_tab.surfacing(tab_text)


if __name__ == "__main__":
    Contero().run()
```
`leak.kv`:
```
#:kivy 1.11.1
#:import ACTION_ICON __main__.ACTION_ICON
BoxLayout:
    orientation: "vertical"
    MDTabs:
        id: ps_tabs
        on_tab_switch: app.on_tab_switch(*args)
        TabList:
            id: ps_tab_list
            text: "flash"
            ScrollView:
                bar_margin: 5
                bar_width: 15
                bar_color: .0, .8, .0, 1
                bar_inactive_color: .5, .5, .5, 1
                effect_cls: "ScrollEffect"
                scroll_type: ["bars", "content"]
                scroll_distance: 5
                scroll_timeout: 50
                MDList:
                    id: ps_list
    MDBottomAppBar:
        MDToolbar:
            id: ps_toolbar
            title: "Destroy a list"
            icon: ACTION_ICON
            type: "bottom"
            on_action_button: app.discovery_request()
            right_action_items: [ ['minus-box-outline', lambda x: app.discovery_clean()], ]


<PowerListItem>:
    IconLeftWidget:
        id: item_left
        icon: "earth"
```

**Comment by HeaTTheatR** [comment]
@Tyrn Ask this question here - https://github.com/kivy/kivy/issues. KivyMD uses Kivy. Therefore, your question is connected with Kivy, and not with KivyMD.

**Comment by Tyrn** [comment]
I'm really sorry, but they referred me back here: [#6824](https://github.com/kivy/kivy/issues/6824). Who could help me?

**Comment by HeaTTheatR** [comment]
@Tyrn https://github.com/kivy/kivy/issues/6824#issuecomment-612918129

**Comment by Tyrn** [comment]
Ah... Thanks! Looks like there's no trace of unhappiness about this well-known problem. No workarounds, too?

**Comment by HeaTTheatR** [comment]
@Tyrn Most likely your question will remain unanswered by the `Kivy` developers.

**Comment by Tyrn** [comment]
You are developing alongside Kivy for some time. You never got inconvenienced by this issue? I've run into it right from the start :(

**Comment by HeaTTheatR** [comment]
@Tyrn Memory is so cheap on modern computers that you don’t have to worry about it with your application with one screen.

**Comment by Tyrn** [comment]
Besides, you can create your own pool of list items and reuse them, so you'll never allocate more than the longest list of the session :)

**Comment by HeaTTheatR** [comment]
@Tyrn https://github.com/kivy/kivy/issues/6824#issuecomment-612979738

**Comment by Tyrn** [comment]
Kivy ListView, whatever it is, is deprecated. [RecycleView](https://kivy.org/doc/stable/api-kivy.uix.recycleview.html) is in order. I'll have to stuff my example with buttons :)

**Comment by Tyrn** [comment]
I did as the Kivy developer suggested: reduced my case study to Kivy widgets. No memory leakage any more, so I put it here for your information. It's up to you to decide whether to make a bug report of it, I suppose.
`leak.py`:
```
from functools import partial
import kivy

kivy.require("1.11.1")
from kivy.utils import platform

print(f"platform: {platform}")

from kivy.lang import Builder

from kivy.app import App
from kivy.uix.button import Button
import gc


class PowerListItem(Button):
    pass


class Contero(App):

    def build(self):
        return Builder.load_file("leak.kv")

    def on_start(self):
        pass

    def discover(self, cnt):
        ids = App.get_running_app().root.ids
        for i in range(cnt):
            item = PowerListItem(
                text="List Item" + f" {i + 1:>2}"
            )
            ids.ps_list.add_widget(item)

    def discovery_clean(self):
        for item in self.root.ids.ps_list.children:
            print(f"item: {item.text}")
        self.root.ids.ps_list.clear_widgets()
        gc.collect()

    def discovery_request(self, item_count=50):
        self.discovery_clean()
        self.discover(item_count)


if __name__ == "__main__":
    Contero().run()
```
`leak.kv`
```
#:kivy 1.11.1
#:import Window kivy.core.window.Window
BoxLayout:
    orientation: "vertical"
    ScrollView:
        bar_margin: 5
        bar_width: 15
        bar_color: .0, .8, .0, 1
        bar_inactive_color: .5, .5, .5, 1
        effect_cls: "ScrollEffect"
        scroll_type: ["bars", "content"]
        scroll_distance: 5
        scroll_timeout: 50
        GridLayout:
            id: ps_list
            padding: dp(4)
            cols: 1
            size_hint_y: None
            height: self.minimum_height
    BoxLayout:
        size_hint: [1, 0.2]
        orientation: "horizontal"
        Button:
            text: "Populate"
            bold: True
            on_press: app.discovery_request()
        Button:
            text: "Clean"
            bold: True
            on_press: app.discovery_clean()


<PowerListItem>:
    bold: True
    size_hint: None, None
    width: Window.width
    height: 90
```
