### ISSUE TITLE
Icons are not displayed on Android

### ISSUE THREAD

**Issue by mkc2019** [kivymd/KivyMD#257]
### Description of the Bug
I noticed that lung icon cannot be properly displayed in Android Device, although it is perfectly fine on PC. Would anyone has any idea why this is happening?

### Code and Logs
```
Builder.load_string("""
<AlertView>
    ScrollView:
        do_scroll_x: False
        do_scroll_y: True
        BoxLayout:
            size_hint_y: None
            height: self.minimum_height
            orientation: "vertical"
            padding: 0, titlebar.height, 0, 0

            # Table
            MDList:
                id: alert_table
                padding: 0,0,0,0
                # High High Rate Alert
                ThreeLineAvatarIconListItem:
                    text: "High Heart Rate"
                    font_style: "H6"
                    secondary_text: "Ward 9A | Bed 27 | Patient 12"
                    tertiary_text: "10:42"
                    bg_color: 1,0,0,.1

                    IconLeftWidget:
                        icon: "heart-pulse"
                        theme_text_color: "Custom"
                        text_color: 1,0,0,1
                    IconRightWidget:
                        icon: "minus"

                # Low Respiration Rate Alert
                ThreeLineAvatarIconListItem
                    text: "Low Respiration Rate"
                    font_style: "H6"
                    secondary_text: "Ward 9A | Bed 10 | Patient 8"
                    tertiary_text: "10:39"
                    bg_color: 1,0,0,.1

                    IconLeftWidget:
                        icon: "lungs"
                        theme_text_color: "Custom"
                        text_color: 1,0,0,1
                    IconRightWidget:
                        icon: "minus"

                # Low Heart Rate Alert
                ThreeLineAvatarIconListItem
                    text: "Low Heart Rate"
                    font_style: "H6"
                    secondary_text: "Ward 9A | Bed 1 | Patient 2"
                    tertiary_text: "10:40"
                    bg_color: 1,1,0,.1

                    IconLeftWidget:
                        icon: "heart-pulse"
                        theme_text_color: "Custom"
                        text_color: 1,.5,0,1
                    IconRightWidget:
                        icon: "minus"

                # Low Stroke Volume Alert
                ThreeLineAvatarIconListItem
                    text: "Low Stroke Volume"
                    font_style: "H6"
                    secondary_text: "Ward 9A | Bed 1 | Patient 2"
                    tertiary_text: "10:40"
                    bg_color: 1,1,0,.1

                    IconLeftWidget:
                        icon: "heart-multiple"
                        theme_text_color: "Custom"
                        text_color: 1,.5,0,1
                    IconRightWidget:
                        icon: "minus"

                # Low Signal Alert
                ThreeLineAvatarIconListItem
                    text: "Weak Signal Strength"
                    font_style: "H6"
                    secondary_text: "Ward 9A | Bed 1 | Patient 2"
                    tertiary_text: "10:40"
                    bg_color: 1,1,0,.1

                    IconLeftWidget:
                        icon: "signal-cellular-1"
                        theme_text_color: "Custom"
                        text_color: 1,.5,0,1
                    IconRightWidget:
                        icon: "minus"

                # Bed Exit Alert
                ThreeLineAvatarIconListItem
                    text: "Bed-Exit Alarm"
                    font_style: "H6"
                    secondary_text: "Ward 9A | Bed 1 | Patient 2"
                    tertiary_text: "10:40"
                    bg_color: 1,1,0,.1

                    IconLeftWidget:
                        icon: "bed-empty"
                        theme_text_color: "Custom"
                        text_color: 1,.5,0,1
                    IconRightWidget:
                        icon: "minus"

                # Sync Alert
                ThreeLineAvatarIconListItem
                    text: "Synchronization Failure"
                    font_style: "H6"
                    secondary_text: "Ward 9A | Bed 1 | Patient 2"
                    tertiary_text: "10:40"
                    bg_color: 1,1,0,.1

                    IconLeftWidget:
                        icon: "sync-alert"
                        theme_text_color: "Custom"
                        text_color: 1,.5,0,1
                    IconRightWidget:
                        icon: "minus"
    TitleBar:
        title: "Alert View"
        id: titlebar
""")

class AlertView(Screen):
    def __init__(self,**kwargs):
        super().__init__(**kwargs)
```

### Screenshots

<details>
<summary>Screenshots</summary>

PC Screen
![Screen Shot PC](https://user-images.githubusercontent.com/55228926/79834906-6940f880-83e0-11ea-9cf9-0cb877dac752.png)

Android Device Screen
![Screen Shot Android Device](https://user-images.githubusercontent.com/55228926/79834913-6ba35280-83e0-11ea-930c-ecedf9b21fe3.jpeg)
</details>

### Versions
* OS: Android 10
* Python: 3.6.9
* Kivy: 1.11.1
* KivyMD: 0.104.0

**Comment by HeaTTheatR** [comment]
@mkc2019 It is not yet known why some icons are not displayed on the Android device.

**Comment by mkc2019** [comment]
Thank you for your quick response. I have verified that the key "lungs" is a valid key of md_icons, and the value it contains is correct too (i.e. \U000F00AF). 

Interestingly, I noticed that all icons with a value that begins with \U cannot be displayed on Android devices. I have no idea why though. Maybe some problem with unicode encoding?

**Comment by HeaTTheatR** [comment]
@mkc2019 Unfortunately, there is no time to fix this error.

**Comment by mkc2019** [comment]
It is okay. Take your time.

In the meantime, as I am creating my own icon, it appears that the definition on BaseRoundButton may be the culprit:

```

<BaseRoundButton>
    canvas:
        Clear
        Color:
            rgba: self._current_button_color if root.icon in md_icons else (0, 0, 0, 0)
        Ellipse:
            size: self.size
            pos: self.pos
            source: self.source if hasattr(self, "source") else ""

    size:
        (dp(48), dp(48)) \
        if not root.user_font_size \
        else (dp(root.user_font_size + 23), dp(root.user_font_size + 23))
    lbl_txt: lbl_txt
    padding: dp(12) if root.icon in md_icons else 0
    theme_text_color: 'Primary'

    MDIcon:
        id: lbl_txt
        icon: root.icon
        font_size:
            root.user_font_size \
            if root.user_font_size \
            else self.font_size
        font_name: root.font_name if root.font_name is not None else self.font_name
        theme_text_color: root.theme_text_color
        text_color: root.text_color
        disabled: root.disabled
        valign: 'middle'
        halign: 'center'
        opposite_colors: root.opposite_colors

```
That line `rgba: self._current_button_color if root.icon in md_icons else (0, 0, 0, 0)` seems quite suspicious to me...

In any case, thanks!
