### ISSUE TITLE
MDCheckbox in OneLineAvatarIconListItem gets updated too frequently + suggested fix

### ISSUE THREAD

**Issue by mkc2019** [kivymd/KivyMD#258]
### Description of the Bug
If I place a MDCheckBox inside a OneLineAvatarIconListItem, when I press the check box, it gets checked and then unchecked immediately. Using logcat I realized that the system considered the button pressed twice, although I only tapped it once. 

### Code and Logs
My kv file:
```
MDList:
  id: alert_table
  padding: 0,0,0,0
  # Switches - HR alert
  OneLineAvatarIconListItem:
      text: "Display Heart Rate Alert"
      font_style: "H6"
      IconLeftWidget:
          icon: "heart-pulse"
      SwitchRightWidget:
          id: doHeartRateAlert
```
My .py file that defines SwitchRightWidget (it was named switch because i originally use MDSwitch)

```
class SwitchRightWidget(IRightBody, MDCheckbox):
    pass
```
### Screenshots
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/55228926/79850933-2f2f2100-83f7-11ea-9660-0fc15906e66d.gif)

### Suggestion
Fix it using min_state_time, as in the method used by kivy button.
```
from time import time

class SwitchRightWidget(IRightBody, MDCheckbox):
    def __init__(self,**kwargs):
        super().__init__(**kwargs)
        self.__touch_time = 0
        self.min_state_time = 0.1

    """The app is so sensitive that one tap is counted twice. Add an IF statement to prevent that."""
    def _do_press(self):
        if time() - self.__touch_time > self.min_state_time:
            self.__touch_time = time()
            super()._do_press()
```

### Versions
* OS: Android 10
* Python: 3.6.9
* Kivy: 1.11.1
* KivyMD: 0.104.0
