### ISSUE TITLE
AttributeError | Problem with MDDropDownMenu

### ISSUE THREAD

**Issue by Felipe738743872** [kivymd/KivyMD#260]
### Description

Hi, I have problems with MDDropDownMenu...
What is wrong?

### main.py

```python
from kivymd.app import MDApp

class Activity(MDApp):
    menu_items = [
        {
            'text': 'my text',
            'icon': 'box',
        }
    ]

Activity().run()
```

### activity.kv

```
#:import MDDropdownMenu kivymd.uix.menu.MDDropdownMenu

ScreenManager:
    Screen:
        name: "menu"

        MDToolbar
            title: "MDDropDownMenu example"
            pos_hint: {"top":1}
            size_hint: 1, 0.1
            left_action_items: [["dots-vertical", lambda x: MDDropdownMenu(items=app.menu_items, width_mult=4).open()]]
```

### Error

```
   File "/Users/felipe/Documents/MyProject/venv/lib/python3.7/site-packages/kivymd/uix/menu.py", line 626, in set_menu_properties
     self._start_coords = self.caller.to_window(
 AttributeError: 'NoneType' object has no attribute 'to_window'
```

### Versions

* OS: Mac High Sierra 10.13.6
* Python: 3.7.6
* Kivy: 1.11.1
* KivyMD: 0.104.0
