### ISSUE TITLE
font_size not working for MDRectangleFlatIconButton

### ISSUE THREAD

**Issue by garantor** [kivymd/KivyMD#307]
### Description of the Bug

 i tried using font_size and text_size for MDRectangleFlatIconButton, is not working, anyway to increase the text size of the button

### Versions
kivymd 0.104.1
* OS: 
* Python: 
* Kivy: 
* KivyMD:

**Comment by allasca** [comment]
@garantor 
what do you mean? 
### MDRectangleFlatIconButton
![](https://cdn.discordapp.com/attachments/440127913837330444/717069391300132924/Screenshot_from_2020-06-02_00-34-56.png)
```
    MDRectangleFlatIconButton:
        text: "Custom size long"
        font_size: 30
        width: 600
```

**Comment by HeaTTheatR** [comment]
The button is automatically sized to fit the font size:

```
    MDRectangleFlatIconButton:
        text: "Custom size long"
        font_size: sp(46)
        pos_hint: {"center_x": .5, "center_y": .5}
```

But if the font size is too large, the text overlaps the button icon:

![Снимок экрана 2020-09-19 в 11 54 52](https://user-images.githubusercontent.com/16930280/93663268-45591000-fa6f-11ea-87db-6a5960eb740a.png)

This is another issue. Therefore, I close the current issue. Feel free to open a new issue.
