### ISSUE TITLE
MDTextField on_error returns black on Dark mode.

### ISSUE THREAD

**Issue by BananaMasterz** [kivymd/KivyMD#312]
### Description of the Bug

The on_error option in Dark mode turns the hint text to black so you end up with black text on black background.

### Code and Logs

```python
from kivy.lang import Builder

from kivymd.app import MDApp

KV = '''
BoxLayout:
    padding: "10dp"

    MDTextField:
        id: text_field_error
        hint_text: "Helper text on error (press 'Enter')"
        helper_text: "There will always be a mistake"
        helper_text_mode: "on_error"
        pos_hint: {"center_y": .5}
'''


class Test(MDApp):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.screen = Builder.load_string(KV)
        self.theme_cls.theme_style = "Dark" #change to "Light" to see the difference

    def build(self):
        self.screen.ids.text_field_error.bind(
            on_text_validate=self.set_error_message,
            on_focus=self.set_error_message,
        )
        return self.screen

    def set_error_message(self, instance_textfield):
        self.screen.ids.text_field_error.error = True


Test().run()


class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

### Screenshots

https://photos.app.goo.gl/QC7DT3SgrfqF6Qv16

### Versions

* OS: Windows 10 Pro
* Python: 3.7
* Kivy: 1.11.0
* KivyMD: v0.104.1

**Comment by HeaTTheatR** [comment]
@BananaMasterz There is no mistake.
![20200519_152625](https://user-images.githubusercontent.com/16930280/82326348-558bb080-99e5-11ea-8c2c-c18ea07382f3.png)

**Comment by wasimafser** [comment]
> @BananaMasterz There is no mistake.

i guess he is using the darker mode ! ( the #121212 background )

**Comment by HeaTTheatR** [comment]
@BananaMasterz `current_hint_text_color`

**Comment by HeaTTheatR** [comment]
```

                MDTextField:
                    id: text_field_error
                    current_hint_text_color: 1, 1, 1, 1
                    hint_text: "Helper text on error (press 'Enter')"
                    helper_text: "Two is my least favorite number"
                    helper_text_mode: "on_error"
```
