### ISSUE TITLE
MDExpansionPanel with MDLabel 

### ISSUE THREAD

**Issue by pitman123** [kivymd/KivyMD#330]
### Description of the Bug

When I try to use MD Label with MD Expansion Panel there is a problem with the MDLabel size at the first use. The MDLabel size does not fit the text. The next time you use MDExpension Panel, everything works fine.

### Code and Logs

```from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.boxlayout import MDBoxLayout
from kivymd.uix.expansionpanel import MDExpansionPanel, MDExpansionPanelOneLine
from kivymd import images_path

KV = '''
<Content>
    adaptive_height: True
    orientation: "vertical"

    MDLabel:
        text: 'text'*100
        size_hint: (1, None)
        size: self.texture_size
        
ScrollView:

    MDGridLayout:
        id: box
        cols: 1
        adaptive_height: True
'''


class Content(MDBoxLayout):
    '''Custom content.'''

class Test(MDApp):
    def build(self):
        return Builder.load_string(KV)

    def on_start(self):
        self.root.ids.box.add_widget(
                MDExpansionPanel(
                    icon=f"{images_path}kivymd_logo.png",
                    content=Content(),
                    panel_cls=MDExpansionPanelOneLine(
                        text="Text",
                    )
                )
            )


Test().run()
```

### Screenshots

<img src="https://user-images.githubusercontent.com/53664786/83163055-da27ae80-a10a-11ea-9f65-989c3d7dae1c.PNG" width="250" height="400"><img src="https://user-images.githubusercontent.com/53664786/83163150-ff1c2180-a10a-11ea-8d18-d40f5a552a56.PNG" width="250" height="400">

### Versions

* OS: Windows 10
* Python: 3.7
* Kivy: 1.11.1
* KivyMD: 0.103.0

**Comment by aprilahijriyan** [comment]
@HeaTTheatR  I also experienced the same thing :(

**Comment by wasimafser** [comment]
@piotrtrojanowski-dev 
does this solve all ?

```
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.boxlayout import MDBoxLayout
from kivymd.uix.expansionpanel import MDExpansionPanel, MDExpansionPanelOneLine
from kivymd import images_path

KV = '''
<Content>
    adaptive_height: True
    orientation: "vertical"

    MDLabel:
        text: 'text'*100

ScrollView:

    MDGridLayout:
        id: box
        cols: 1
        adaptive_height: True
'''


class Content(MDBoxLayout):
    '''Custom content.'''

class Test(MDApp):
    def build(self):
        return Builder.load_string(KV)

    def on_start(self):
        self.root.ids.box.add_widget(
                MDExpansionPanel(
                    icon=f"{images_path}kivymd_logo.png",
                    content=Content(),
                    panel_cls=MDExpansionPanelOneLine(
                        text="Text",
                    )
                )
            )
        self.root.ids.box.add_widget(
                MDExpansionPanel(
                    icon=f"{images_path}kivymd_logo.png",
                    content=Content(),
                    panel_cls=MDExpansionPanelOneLine(
                        text="Text2",
                    )
                )
            )


Test().run()
```

**Comment by aprilahijriyan** [comment]
@wasimafser I don't think this issue has really been solved!
Try the content below, on my computer the case is still the same as this issue.

```
<Content@MDBoxLayout>:
    orientation: "vertical"
    padding: dp(15)
    spacing: dp(10)
    adaptive_height: True

    MDGridLayout:
        cols: 5
        adaptive_height: True
        spacing: dp(20)

        MDBoxLayout:
            orientation: "vertical"
            adaptive_height: True

            MDLabel:
                text: "No"
                size_hint_y: None
                height: self.texture_size[1]

            MDSeparator:
                height: 2

        MDBoxLayout:
            orientation: "vertical"
            adaptive_height: True

            MDLabel:
                text: "Tanggal"
                size_hint_y: None
                height: self.texture_size[1]

            MDSeparator:
                height: 2

        MDBoxLayout:
            orientation: "vertical"
            adaptive_height: True

            MDLabel:
                text: "Anamnesa"
                size_hint_y: None
                height: self.texture_size[1]

            MDSeparator:
                height: 2

        MDBoxLayout:
            orientation: "vertical"
            adaptive_height: True

            MDLabel:
                text: "Tindakan"
                size_hint_y: None
                height: self.texture_size[1]

            MDSeparator:
                height: 2

        MDBoxLayout:
            orientation: "vertical"
            adaptive_height: True

            MDLabel:
                text: "Terapi"
                size_hint_y: None
                height: self.texture_size[1]

            MDSeparator:
                height: 2

    ScrollView:
        MDList:
            id: daftar_rm

    Widget:
        size_hint_y: None
        height: dp(20)
```

**Comment by wasimafser** [comment]
@aprilahijriyan , remove `size_hint_y : None` and height properties from the MDLabels you want to use.
If the problem still exists, make a full example of how you want it to be ( with the Python code ) and share it here.

With the code you provided we can't even guess which part you're using for the Content

**Comment by pitman123** [comment]
@HeaTTheatR @wasimafser This solution is bad. I tried this way. In this case Label have pernament size. Try "text"* 300 and tetx doesnt fit to Label.

**Comment by wasimafser** [comment]
> This solution is bad. 
Bad if you didn't specify what you wanted, try being more specific with providing details of what you want to achieve.


> I tried this way. In this case Label have pernament size. Try "text"* 300 and tetx doesnt fit to Label.

For the example you provided , text*100 , it was correct, so you can't blame me for that right ??

Please let me know about what you wanted to have in that content, so that I could try doing that.

**Comment by aprilahijriyan** [comment]
@wasimafser hufft seems like this problem is solved, if I delete `adaptive_height` on MDGridLayout.

**Comment by pitman123** [comment]
@wasimafser ok, maybe the exmaple was not precise, I want to have Label which will  fit the text independently of how much the text is. In your sultion if i do "text"* 10 Label is too big. If i do 'text' * 300 Label is too small.

**Comment by wasimafser** [comment]
try removing `adaptive_height` of the box layout.

And adding :
```
size_hint: (1, None)
height: self.texture_size[1]
```

To MDLabel

**Comment by piotrtrojanowski-dev** [comment]
@wasimafser  In this case MDLabel increases after each use
```<Content>
    orientation: "vertical"

    MDLabel:
        text: 'text'*100
        size_hint: (1, None)
        height: self.texture_size[1]

ScrollView:

    MDGridLayout:
        id: box
        cols: 1
        adaptive_height: True
'''```

**Comment by pitman123** [comment]
@wasimafser  In this case MDLabel increases after each use MDExpansionPanel

**Comment by wasimafser** [comment]
> @wasimafser In this case MDLabel increases after each use MDExpansionPanel

Well... I just noticed, try adding 10 Expansion items, I guess the scroll view of yours won't work. 
If you know how to make it work, maybe this problem will also be solved. Try it ? ( It's just related to the child / parent widget height )

**Comment by pitman123** [comment]
@wasimafser I've already tried with more Expension items, but its still work the same. The scroll wiew works right.

**Comment by p0lygun** [comment]
ok so the problem is in 
height of the content class 
see the height attr 
### Opening the expansion panel for the first time
![image](https://user-images.githubusercontent.com/22869882/91300754-6fe1e100-e7c1-11ea-9493-dc96d53ff22e.png)
### Opening the expansion panel for the second time
![image](https://user-images.githubusercontent.com/22869882/91301027-dff06700-e7c1-11ea-98d5-84c477651b45.png)

the height of the content cls 
in [open_panel](https://github.com/kivymd/KivyMD/blob/master/kivymd/uix/expansionpanel.py#L367) 
the height of the content panel is not correct because of that it behaves like that

**Comment by gregynard** [comment]
Hello everyone. Do we have any solutions for this? The Issue is still the same for me.

**Comment by HeaTTheatR** [comment]
@gregynard No solution yet...

**Comment by gregynard** [comment]
@HeaTTheatR noted on this. I just notice that the problem occurs when you used MDlabel with adaptive_height: True. 

Thanks!

**Comment by HeaTTheatR** [comment]
@piotrtrojanowski-dev 

```
#:import Window kivy.core.window.Window


<Content>
    adaptive_height: True
    orientation: "vertical"

    MDLabel:
        text: 'text' * 100
        adaptive_height: True
        text_size: Window.width, None
```

This seems to fix the issue...
