### ISSUE TITLE
MDFloatingActionButtonSpeedDial & MDTabs crash, blank screen

### ISSUE THREAD

**Issue by allasca** [kivymd/KivyMD#336]
### Description of the Bug

after opening MDFloatingActionButtonSpeedDial and then change tab will result blank screen

### Code and Logs

```
from kivy.lang import Builder
from kivymd.app import MDApp
from kivy.uix.boxlayout import BoxLayout
from kivymd.uix.tab import MDTabsBase

KV = '''
<Tab1>:
    BoxLayout:
        MDFloatingActionButtonSpeedDial:
            data: app.data

BoxLayout:
    MDTabs:
        Tab1:
            id: tab1
            text: "tab 1"
        Tab2:
            id: tab2
            text: "tab 2"
'''
class Tab1(BoxLayout, MDTabsBase):
    pass
class Tab2(BoxLayout, MDTabsBase):
    pass
class MainApp(MDApp):
    data = {
        'language-python': 'Python',
        'language-php': 'PHP',
        'language-cpp': 'C++',
    }
    def build(self):
        return Builder.load_string(KV)

MainApp().run()
```

### Screenshots

[https://cdn.discordapp.com/attachments/566885924361732097/716353971333103646/Peek_2020-05-31_01-10.gif](https://cdn.discordapp.com/attachments/566885924361732097/716353971333103646/Peek_2020-05-31_01-10.gif)
![](https://cdn.discordapp.com/attachments/566885924361732097/716353971333103646/Peek_2020-05-31_01-10.gif)

**Comment by Starli8ht** [comment]
Any news on that issue ? This feature is really handsome but I can't use it with this issue.

**Comment by HeaTTheatR** [comment]
@Starli8ht This issues not closed ... In a few days I will return to the development of the library and fix all the bugs.

**Comment by Starli8ht** [comment]
I know some of you are making a lot of dev on buttons library, but for those who need a quick fix, here is mine (it's working for me, BottomNav is not hidden anymore).
I changed in \kivymd\uix\button.py (l.1665) MDFloatingRootButton by : 
root_button = MDFloatingActionButton(on_release=self.open_stack)
root_button.md_bg_color = self.theme_cls.bg_normal
root_button.text_color = self.theme_cls.primary_color

MDFloatingRootButton  seems to be the problem, don't know why.

**Comment by HeaTTheatR** [comment]
This strange behavior is due to the canvas instructions (https://github.com/kivymd/KivyMD/blob/master/kivymd/uix/button.py#L757):

```
<BaseFloatingRootButton>
    theme_text_color: "Custom"
    md_bg_color: self.theme_cls.primary_color
    
    canvas.before:
         PushMatrix
         Rotate:
             angle: self._angle
             axis: (0, 0, 1)
             origin: self.center
     canvas.after:
         PopMatrix
```

The canvas instructions will be commented out, preventing the main button from rotating when opening the button stack. This temporarily solves this problem. Until a suitable solution is found.
