### ISSUE TITLE
How to increase MDIcon icon size?

### ISSUE THREAD

**Issue by jaredliw** [kivymd/KivyMD#342]

**Comment by HeaTTheatR** [comment]
@jaredliw https://kivymd.readthedocs.io/en/latest/components/button/index.html#mdiconbutton

**Comment by mp-007** [comment]
If you don't want a button, changing the font_size was working for me:
```
MDIcon:
    icon: 'account-cog'		
    font_size : 48
```

**Comment by HeaTTheatR** [comment]
@marcets 
![Снимок экрана 2020-06-03 в 07 58 57](https://user-images.githubusercontent.com/16930280/83597501-27bf7380-a570-11ea-8bc8-c108463b3498.png)

**Comment by mp-007** [comment]
If you use MDIcon, user_font_size doesn't work. See my exemple:

```
from kivy.lang import Builder

from kivymd.app import MDApp

KV = '''
Screen:

    BoxLayout:

        orientation: 'vertical'  
        
        BoxLayout:
     
            MDIconButton:
            	pos: self.parent.pos
            	size: self.parent.size               
                icon: "android"
                user_font_size: "24sp"
        
        BoxLayout:
        
            MDIconButton:
            	pos: self.parent.pos
            	size: self.parent.size         
                icon: "android"
                user_font_size: "64sp"
    
        BoxLayout:
    
            MDIconButton:
            	pos: self.parent.pos
            	size: self.parent.size             
                icon: "android"
                user_font_size: "72sp"
    
        BoxLayout:

            MDIcon:
            	pos: self.parent.pos
            	size: self.parent.size             
                icon: "android"
                user_font_size: "24sp"
                halign:'center'

        BoxLayout:

            MDIcon:
            	pos: self.parent.pos
            	size: self.parent.size             
                icon: "android"
                user_font_size: "64sp"
                halign:'center'

        BoxLayout:

            MDIcon:
            	pos: self.parent.pos
            	size: self.parent.size             
                icon: "android"
                user_font_size: "72sp"
                halign:'center'

        BoxLayout:

            MDIcon:
            	pos: self.parent.pos
            	size: self.parent.size             
                icon: "android"
                font_size: dp(24) 
                halign:'center'

        BoxLayout:

            MDIcon:
            	pos: self.parent.pos
            	size: self.parent.size             
                icon: "android"
                font_size: dp(64)  
                halign:'center'

        BoxLayout:

            MDIcon:
                
            	pos: self.parent.pos
                size: self.parent.size   
                icon: "android"
                font_size: dp(72) 
                halign:'center'
```

![image](https://user-images.githubusercontent.com/19823482/83638968-fea2e100-a577-11ea-8f77-537abe9ad4e1.png)


In the case  you are using the MDIconButton, it's seem the _no_ripple_effet=True doesn't work. So you always have a ripple effect when you click on the button (maybe it's something you don't want).

**Comment by HeaTTheatR** [comment]
@marcets For `MDIcon` class you must use the `font_style` parameter.

**Comment by mp-007** [comment]
Why in the documentation it say to not use font_style?

https://kivymd.readthedocs.io/en/latest/components/label/index.html#mdicon

![image](https://user-images.githubusercontent.com/19823482/83660895-6c103b00-a593-11ea-8a57-6593c571652f.png)

I also tried and it doesn't work.

**Comment by HeaTTheatR** [comment]
@marcets Yes it will not work

**Comment by HeaTTheatR** [comment]
@marcets Use just `font_size: "200sp"`

**Comment by HeaTTheatR** [comment]
@marcets 
```python
MDIcon:
    icon: "git"
    font_size: "200sp"
```

**Comment by HeaTTheatR** [comment]
@marcets 
![Снимок экрана 2020-06-03 в 19 20 29](https://user-images.githubusercontent.com/16930280/83661818-60426a00-a5cf-11ea-8f0d-2d544f7693fc.png)

**Comment by marcets** [comment]
You use font_size like I already suggest. You don't use font_style.

**Comment by mp-007** [comment]
Most of the time, we should use "sp" unstead of "dp" for MDIcon.

**Comment by Arctic4161** [comment]
> If you use MDIcon, user_font_size doesn't work. See my exemple:
> 
> ```
> from kivy.lang import Builder
> 
> from kivymd.app import MDApp
> 
> KV = '''
> Screen:
> 
>     BoxLayout:
> 
>         orientation: 'vertical'  
>         
>         BoxLayout:
>      
>             MDIconButton:
>             	pos: self.parent.pos
>             	size: self.parent.size               
>                 icon: "android"
>                 user_font_size: "24sp"
>         
>         BoxLayout:
>         
>             MDIconButton:
>             	pos: self.parent.pos
>             	size: self.parent.size         
>                 icon: "android"
>                 user_font_size: "64sp"
>     
>         BoxLayout:
>     
>             MDIconButton:
>             	pos: self.parent.pos
>             	size: self.parent.size             
>                 icon: "android"
>                 user_font_size: "72sp"
>     
>         BoxLayout:
> 
>             MDIcon:
>             	pos: self.parent.pos
>             	size: self.parent.size             
>                 icon: "android"
>                 user_font_size: "24sp"
>                 halign:'center'
> 
>         BoxLayout:
> 
>             MDIcon:
>             	pos: self.parent.pos
>             	size: self.parent.size             
>                 icon: "android"
>                 user_font_size: "64sp"
>                 halign:'center'
> 
>         BoxLayout:
> 
>             MDIcon:
>             	pos: self.parent.pos
>             	size: self.parent.size             
>                 icon: "android"
>                 user_font_size: "72sp"
>                 halign:'center'
> 
>         BoxLayout:
> 
>             MDIcon:
>             	pos: self.parent.pos
>             	size: self.parent.size             
>                 icon: "android"
>                 font_size: dp(24) 
>                 halign:'center'
> 
>         BoxLayout:
> 
>             MDIcon:
>             	pos: self.parent.pos
>             	size: self.parent.size             
>                 icon: "android"
>                 font_size: dp(64)  
>                 halign:'center'
> 
>         BoxLayout:
> 
>             MDIcon:
>                 
>             	pos: self.parent.pos
>                 size: self.parent.size   
>                 icon: "android"
>                 font_size: dp(72) 
>                 halign:'center'
> ```
> 
> ![image](https://user-images.githubusercontent.com/19823482/83638968-fea2e100-a577-11ea-8f77-537abe9ad4e1.png)
> 
> In the case you are using the MDIconButton, it's seem the _no_ripple_effet=True doesn't work. So you always have a ripple effect when you click on the button (maybe it's something you don't want).

I have been looking everywhere on how to resize and this worked for me.

**Comment by Makieyot** [comment]
User font size work for me but icon size and font size doesn't work

**Comment by HeaTTheatR** [comment]
@Makieyot 
https://kivymd.readthedocs.io/en/latest/components/button/#mdiconbutton
![Снимок экрана 2022-07-12 в 18 49 43](https://user-images.githubusercontent.com/16930280/178534323-edb4b503-88b8-4589-8669-1690f0065988.png)

**Comment by Sahil-pixel** [comment]
Size of MDIcon is not changing 
kivymd version  2.0.1.dev0,
MDIcon:
    	icon:'trophy'
    	#theme_font_size: "Custom"
    	font_size:'55sp'

**Comment by HeaTTheatR** [comment]
@Sahil-pixel 
```
    MDIcon:
        icon: "git"
        theme_font_size: "Custom"
        font_size: "45sp"
```
