### ISSUE TITLE
increment the size of the icon on the MDFloatingActionButton

### ISSUE THREAD

**Issue by AndresRamosC** [kivymd/KivyMD#349]
### Description of the Feature
iḿ doing an app for a medium size device so the button is size (dp(95), dp(95)) and the icon looks small inside of it,
is there any way that i can make the icon bigger?

### Screenshots
![image](https://user-images.githubusercontent.com/51414745/84305176-3634fe80-ab1f-11ea-9b9a-5f3e45cc9a30.png)

### Versions

* OS: 
* Python: 3.7
* Kivy: '1.9.0'
* KivyMD: 0.1.2

**Comment by HeaTTheatR** [comment]
@AndresRamosC 
![Снимок экрана 2020-06-10 в 21 38 17](https://user-images.githubusercontent.com/16930280/84305444-c34d7700-ab62-11ea-9762-83465e6b302e.png)

https://kivymd.readthedocs.io/en/latest/components/button/index.html#kivymd.uix.button.MDIconButton

**Comment by AndresRamosC** [comment]
i dont know if im using it correctly as it doesnt work
here is my code:

```
MDFloatingActionButton:
        id: float_settings_btn
        icon: 'bluetooth-audio'
        user_font_size: "72sp"
        size: (dp(95), dp(95))
        opposite_colors: True
        elevation_normal: 8
        pos_hint: {'center_x': 0.85, 'center_y': 0.080}
        md_bg_color: (0.05098,0.27843,0.63137,.95)
        theme_text_color: 'Custom'
        text_color: (1,1,1,1)
        on_release: app.show_settings()
```
