### ISSUE TITLE
Can KivyMD change font family?

### ISSUE THREAD

**Issue by sdayu** [kivymd/KivyMD#35]
I use KivyMD to display other languages using a special character not limited to roman, but the program did not display the character from other languages. In KIvy, I can add default font to the program, but KivyMD dit not display it. Is KivyMD support other fonts?

**Comment by HeaTTheatR** [comment]
```python
            MDLabel:
                text: '  Цитаты святых'
                bold: True
                font_size: '20sp'
                font_name: 'data/font/gothic.ttf'
                color: 0, 0, 0, 1
```
![Снимок экрана 2019-04-16 в 16 28 38](https://user-images.githubusercontent.com/16930280/56213492-cdf6a400-6064-11e9-9dcb-e4a0972bb43d.png)

**Comment by sdayu** [comment]
Thank you.

**Comment by sdayu** [comment]
It ok for Label, could you check in other widgets like MDFillRoundFlatButton. Thank you.

**Comment by sdayu** [comment]
This is my result
```
                MDFillRoundFlatButton:
                    color: 0, 0, 0, 1
                    bold: True
                    font_size: '30sp'
                    font_name: 'fonts/THSarabunNew.ttf'
                    text: 'Xลืมรหัสผ่านX
```

![Screenshot from 2019-04-16 21-10-15](https://user-images.githubusercontent.com/701076/56216750-35741a00-608c-11e9-98e0-37c26a4eccf0.png)
