### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'primary_palette' error in MDtextField example in wiki

### ISSUE THREAD

**Issue by Soichi-Tamashiro** [kivymd/KivyMD#370]
### Description of the Bug

Hi, I found an issue when using the Example of using MDTextField in the wiki:
```
     self.theme_cls.primary_palette = "Blue"
 AttributeError: 'NoneType' object has no attribute 'primary_palette'
```
### Code and Logs

```
from kivy.lang import Builder
from kivy.factory import Factory
from kivymd.app import MDApp

Builder.load_string(
    """
<ExampleTextFields@BoxLayout>:
    orientation: "vertical"

    MDToolbar:
        id: toolbar
        title: app.title
        md_bg_color: app.theme_cls.primary_color
        background_palette: "Primary"
        elevation: 10
        left_action_items: [["menu", lambda x: None]]

    ScrollView:

        BoxLayout:
            orientation: "vertical"
            size_hint_y: None
            height: self.minimum_height
            padding: dp(48)
            spacing: 10

            MDTextField:
                hint_text: "No helper text"

            MDTextField:
                hint_text: "Helper text on focus"
                helper_text: "This will disappear when you click off"
                helper_text_mode: "on_focus"

            MDTextField:
                hint_text: "Persistent helper text"
                helper_text: "Text is always here"
                helper_text_mode: "persistent"

            MDTextField:
                id: text_field_error
                hint_text:
                    "Helper text on error (Hit Enter with two characters here)"
                helper_text: "Two is my least favorite number"
                helper_text_mode: "on_error"

            MDTextField:
                hint_text: "Max text length = 10"
                max_text_length: 10

            MDTextField:
                hint_text: "required = True"
                required: True
                helper_text_mode: "on_error"

            MDTextField:
                multiline: True
                hint_text: "Multi-line text"
                helper_text: "Messages are also supported here"
                helper_text_mode: "persistent"

            MDTextField:
                hint_text: "color_mode = \'accent\'"
                color_mode: "accent"

            MDTextField:
                hint_text: "color_mode = \'custom\'"
                color_mode: "custom"
                helper_text_mode: "on_focus"
                helper_text:
                    "Color is defined by \'line_color_focus\' property"
                line_color_focus:
                    # This is the color used by the textfield
                    self.theme_cls.opposite_bg_normal

            MDTextField:
                hint_text: "disabled = True"
                disabled: True
"""
)


class MainApp(MDApp):
    def __init__(self, **kwargs):
        self.title = "KivyMD Examples - Text Fields"
        self.theme_cls.primary_palette = "Blue"
        super().__init__(**kwargs)

    def build(self):
        self.root = Factory.ExampleTextFields()


if __name__ == "__main__":
    MainApp().run()
```
[INFO   ] [Logger      ] Record log in /home/soichi/.kivy/logs/kivy_20-06-25_39.txt
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "/home/soichi/.local/lib/python3.7/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.7.7 (default, Mar 10 2020, 15:16:38) 
[GCC 7.5.0]
[INFO   ] [Python      ] Interpreter at "/usr/bin/python3.7"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [KivyMD      ] v0.104.1
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 440.59'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'GeForce GTX 1060/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
 Traceback (most recent call last):
   File "main.py", line 94, in <module>
     MainApp().run()
   File "main.py", line 86, in __init__
     self.theme_cls.primary_palette = "Blue"
 AttributeError: 'NoneType' object has no attribute 'primary_palette'

### Versions

* OS: Ubuntu18.04
* Python: 3.7.7
* Kivy: 1.11.1
* KivyMD: 0.104.1
