### ISSUE TITLE
changing the primary_palette ,primary_hue and theme_styley the user

### ISSUE THREAD

**Issue by ghost** [kivymd/KivyMD#375]
I want to make the user change the  primary_palette ,primary_hue and theme_styley by the user and i don't want to use the MDThemePicker if that possible
I tried this 
main.py

```python
from kivymd.app import MDApp
from kivy.lang import Builder
from kivy.uix.label import Label
from kivy.uix.popup import Popup

from kivymd.uix.screen import Screen
from kivymd.uix.button import MDRectangleFlatButton
from kivy.properties import StringProperty
from kivymd.uix.picker import MDThemePicker

class SetPopup(Popup):
    pass

class Kivy_for_AllApp(MDApp):
    primary_palette = StringProperty('Red')
    primary_hue = StringProperty('A700')
    theme_style = StringProperty('Light')

    def build(self):
        self.theme_cls.primary_palette = self.primary_palette
        self.theme_cls.primary_hue = self.primary_hue
        self.theme_cls.theme_style = self.theme_style
        return Builder.load_file("main.kv")

    def opensetpopup(self):
        SetPopup().open()


Kivy_for_AllApp().run()
```

main.kv

```
Screen:
    FloatLayout:
        Button:
            pos_hint: {'x': .7, 'y': .1}
            size_hint: .2,.1
            text: 'Set'
            on_press: app.opensetpopup()
    MDRectangleFlatButton:
        text:'Hello World'
        pos_hint:{'center_x': 0.5, 'center_y': 0.5}


<SetPopup>:
    title: 'choose the them specifications'

    BoxLayout:
        orientation: 'vertical'
        GridLayout:
            cols: 2
            spacing: [20,20]
            padding_y:10
            Spinner:
                text: 'primary_palette'
                id: primary_palette_spinner_id
                values: ('Red', 'Pink', 'Purple', 'DeepPurple', 'Indigo', 'Blue', 'LightBlue', 'Cyan', 'Teal', 'Green', 'LightGreen', 'Lime', 'Yellow', 'Amber', 'Orange', 'DeepOrange', 'Brown', 'Gray', 'BlueGray')
            Label:
                text: 'choose your app\nprimary_palette color'
                font_size: .1*self.width
            Spinner:
                text: 'primary_hue'
                id: primary_hue_spinner_id
                values: ('50', '100', '200', '300', '400', '500', '600', '700', '800', '900', 'A100','A200','A400', 'A700')
            Label:
                text: 'choose your app\nprimary_hue color'
                font_size: .1*self.width
            Spinner:
                text: 'theme_style'
                id: theme_style_spinner_id
                values: ('Dark' , 'Light')
            Label:
                text: 'choose your app\ntheme_style color'
                font_size: .1*self.width
        BoxLayout:
            size_hint_y: .15
            Button:
                text: 'Set'
                on_press:
                    app.primary_palette = primary_palette_spinner_id.text
                    app.primary_hue = primary_hue_spinner_id.text
                    app.theme_style = theme_style_spinner_id.text
                    root.dismiss()

```
the UI work fine the users changes not appears
