### ISSUE TITLE
The MDFileManager crashes on android

### ISSUE THREAD

**Issue by jemdl1998** [kivymd/KivyMD#386]
### Description of the Bug

When you open MDFileManager in the android root the app crashes. The same thing happens to me if I try to use the example from the file manager documentation. I don't know what was going on.
This is the last thing I get with logcat

### Code and Logs

```
from kivymd.app import MDApp
from kivy.uix.boxlayout import BoxLayout
from kivymd.uix.list import MDList
from kivymd.uix.list import OneLineIconListItem,IconLeftWidget
from kivy.uix.screenmanager import ScreenManager,Screen
from kivy.uix.scrollview import ScrollView
from kivymd.uix.filemanager import MDFileManager
from PIL import Image
from android.storage import primary_external_storage_path


class mainApp(MDApp):
            
    def build(self):
        self.theme_cls.theme_style = 'Dark'
        
class FileExplorer(Screen):
    def __init__(self,**kwargs):
        super(FileExplorer,self).__init__(**kwargs)
        self.contador = 0
        self.SD_CARD = primary_external_storage_path()
        
        self.filemanager= MDFileManager(current_path=self.SD_CARD,exit_manager=self.exit_manager)
        self.filemanager.previous = True
        #self.filemanager.ext = ['.webp']
        
        
    def showManager(self):
        self.filemanager.show(self.SD_CARD+'/WhatsApp')

    def exit_manager(self,*args):
        self.filemanager.close()
        
    def init_explorador(self):
        pass

if __name__ == "__main__":
    
    mainApp().run()
```

Kv File:

```
NavigationLayout:
    id:Nav
    ScreenManager:
        id: sm
        Screen:
            name: 'principal'
            id: principal
        FileExplorer:
            id:file
            name:'file'
         

    MDNavigationDrawer:
        orientation: "vertical"
        padding: "8dp"
        spacing: "8dp"
        id:navigation
        

        AnchorLayout:
            anchor_x: 'left'
            size_hint_y: None
            height: avatar.height
            Image:
                id: avatar
                size_hint: None, None
                size: "56dp", "56dp"
                source: "bitmap.png"
        
        MDLabel:
            text: "Webp2png"
            size_hint_y: None
        ScrollView:
            MDList:    
                OneLineIconListItem:
                    text: 'File Manager'
                    on_press: Nav.ids.file.showManager();Nav.ids.sm.current='file'
                    on_release: Nav.ids.navigation.set_state(new_state='close')
                    IconLeftWidget:
                        icon: 'folder'
                        on_press: None
                        on_release: None                   
<FileExplorer>:
```

Log

### Screenshots

```
[INFO   ] [Base        ] Leaving application in progress...
07-04 23:05:32.224 19511 19539 I python  :  Traceback (most recent call last):
07-04 23:05:32.225 19511 19539 I python  :    File "/home/jesus/Documentos/kivy/prueba-almacenamiento/.buildozer/android/app/main.py", line 43, in <module>
07-04 23:05:32.225 19511 19539 I python  :    File "/home/jesus/Documentos/kivy/prueba-almacenamiento/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/app.py", line 855, in run
07-04 23:05:32.226 19511 19539 I python  :    File "/home/jesus/Documentos/kivy/prueba-almacenamiento/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/base.py", line 504, in runTouchApp
07-04 23:05:32.227 19511 19539 I python  :    File "/home/jesus/Documentos/kivy/prueba-almacenamiento/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/core/window/window_sdl2.py", line 747, in mainloop
07-04 23:05:32.227 19511 19539 I python  :    File "/home/jesus/Documentos/kivy/prueba-almacenamiento/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/core/window/window_sdl2.py", line 479, in _mainloop
07-04 23:05:32.228 19511 19539 I python  :    File "/home/jesus/Documentos/kivy/prueba-almacenamiento/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/base.py", line 339, in idle
07-04 23:05:32.228 19511 19539 I python  :    File "/home/jesus/Documentos/kivy/prueba-almacenamiento/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/clock.py", line 591, in tick
07-04 23:05:32.229 19511 19539 I python  :    File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
07-04 23:05:32.230 19511 19539 I python  :    File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
07-04 23:05:32.230 19511 19539 I python  :    File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
07-04 23:05:32.231 19511 19539 I python  :    File "kivy/_clock.pyx", line 154, in kivy._clock.ClockEvent.tick
07-04 23:05:32.231 19511 19539 I python  :    File "kivy/_clock.pyx", line 86, in kivy._clock.ClockEvent.get_callback
07-04 23:05:32.232 19511 19539 I python  :    File "/home/jesus/Documentos/kivy/prueba-almacenamiento/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/weakmethod.py", line 56, in is_dead
07-04 23:05:32.234 19511 19539 I python  :  ReferenceError: weakly-referenced object no longer exists
07-04 23:05:32.234 19511 19539 I python  : Python for android ended.

```

* OS: Android
* Python: 3.8.3
* Kivy: 1.11.1
* KivyMD: 0.104.1
