### ISSUE TITLE
Expansion Panel in ScrollView in Tabs Error

### ISSUE THREAD

**Issue by tommclaughlinjr** [kivymd/KivyMD#387]
Hello all,

I can make a series of expansion panels just fine until I put them into a tab in a scrollview. It also effects the buttons. 
It seems as if the tab is blocking the on_release from getting to the buttons or anything else. Their animations are stopped and they don't fire unless I hold down the mouse buttons for a second. 

In a Tab:
![image](https://user-images.githubusercontent.com/22772211/86542177-53bc7480-bee1-11ea-9c92-e2c468454a9c.png)

Not in a Tab:
![image](https://user-images.githubusercontent.com/22772211/86542203-9aaa6a00-bee1-11ea-8ab7-5dda364b0ce7.png)

Everything works as it should until I use a scroll view in a tab. I have checked with boxlayouts and gridlayouts in tabs and they have worked out fine. However, just an expansion panel in a scroll view in a tab does not work. 

Code:
```
NavigationLayout:
    ScreenManager:
        #MainScreen:
        Screen:
            VBox:
                MDToolbar:
                    title: "TradeCraft"
                    right_action_items: [["android-messages", lambda x: drawer.set_state("toggle", animation=True)], ["dots-vertical", lambda x: app.show_theme_picker()]]

                MDBottomNavigation:
                    panel_color: app.theme_cls.accent_color
                    MDBottomNavigationItem:
                        name: 'home'
                        text: 'Main Menu'
                        icon: 'home'
                        HomeMenu:

                    #This one is not working unless I hold the the mouse button for a long time
                    MDBottomNavigationItem:
                        name: 'trade'
                        text: 'Manual Trade'
                        icon: 'folder-edit'
                        MDTabs:
                            background_color: app.theme_cls.primary_color
                            id: my_tabs
                            TradeCont:
                                text:'Test1'

                        MDFloatingActionButton:
                            icon: "plus"
                            opposite_colors: True
                            elevation_normal: 8
                            md_bg_color: app.theme_cls.primary_color

                            on_release: app.add_coin_dialog()

                    #This works but it is not in a tab
                    MDBottomNavigationItem:
                        name: 'bot'
                        text: 'Trading Bot'
                        icon: 'robot'
                        TradeCont:
                        MDLabel:
                            text: 'I programming of C++'
                            halign: 'center'

<TradeContent>:
    adaptive_height: True

    TwoLineIconListItem:
        text: "(050)-123-45-67"
        secondary_text: "Mobile"

        IconLeftWidget:
            icon: 'phone'


<TradeCont>:
    GridLayout:
        cols: 1
        size_hint_y: None
        height: self.minimum_height
        id: box
       
       #multiple buttons as sometimes the 1st widget never worked
        MDFlatButton:
            text: 'add trade'
            on_release:
                root.add_trade()
                print('adding')
        MDFlatButton:
            text: 'add trade'
            on_release:
                root.add_trade()
                print('adding')
        MDFlatButton:
            text: 'add trade'
            on_release:
                print('adding')
                root.add_trade()


class TradeCont(ScrollView, MDTabsBase):
    def add_trade(self):

        ep = MDExpansionPanel(
                icon="estop.png",  # panel icon
                content=TradeContent(),  # panel content
                panel_cls=MDExpansionPanelOneLine(text="Secondary text")

            )
        self.ids.box.add_widget(ep)
```

Any thoughts on what it could be or what I am doing wrong?

Thanks!

**Comment by tommclaughlinjr** [comment]
Doing some additional testing with other widgets, it seems that the buttons get stuck with a MDCard as well:
![image](https://user-images.githubusercontent.com/22772211/86604299-30420a00-bf73-11ea-8140-8e117b5ab78e.png)
I added a 'on_release: print('test')' and the buttons never printed test unless I hold down the mouse button for a few seconds. 
It does seem as if the tabs are 'consuming' the on_release trigger before the widgets

**Comment by HeaTTheatR** [comment]
@tommclaughlinjr https://discordapp.com/channels/566880874789076992/618108815774056488/715460114378915933

**Comment by HeaTTheatR** [comment]
@tommclaughlinjr 
![Снимок экрана 2020-07-06 в 20 09 40](https://user-images.githubusercontent.com/16930280/86620253-afabf980-bfc4-11ea-8f84-baadb26e6228.png)

**Comment by tommclaughlinjr** [comment]
.py
```
from kivy.uix.boxlayout import BoxLayout
from kivymd.app import MDApp
from kivymd.uix.boxlayout import MDBoxLayout
from kivy.lang import Builder
from kivymd.uix.tab import MDTabsBase
from kivymd.uix.expansionpanel import MDExpansionPanel, MDExpansionPanelOneLine, MDExpansionPanelTwoLine
from kivymd.uix.card import MDCard

class MyTradeCard(MDCard):
    pass

class TradeContent(MDBoxLayout):
    pass

class MyTradeTab(BoxLayout, MDTabsBase):
    '''Class implementing content for a tab.'''
    def add_ep(self):

        ep = MDExpansionPanel(
                icon="logo.png",  # panel icon
                content=TradeContent(),  # panel content
                panel_cls=MDExpansionPanelOneLine(text="Secondary text")

            )
        self.ids.box.add_widget(ep)

    def add_c(self):

        c = MyTradeCard()
        self.ids.box.add_widget(c)


class CC2App(MDApp):
    dialog = None
    my_data = {"bitcoin": "Add Trade Pair",
               "cart-arrow-down": "Add Buy",
               "cart-arrow-up": "Add Sell",
               "cart-remove": "Add Stop",
               "sync": "Add Loop"
               }

    def build(self):
        self.theme_cls.primary_palette = 'Indigo'
        self.theme_cls.accent_palette = 'Gray'
        return Builder.load_file('forgithub.kv')

    def my_callback(self, instance):
        print(instance.icon)


if __name__ == '__main__':
    CC2App().run()
```

.kv
```
<MyTradeCard>:
    orientation: "vertical"
    border_radius: '50dp'
    focus_behavior: True
    elevation: 12
    padding: "8dp"
    size_hint_y: None
    height: self.minimum_height
    pos_hint: {"center_x": .5, "center_y": .5}
    MDBoxLayout:
        orientation: 'horizontal'
        adaptive_height: True
        MDLabel:
            text: "Buy X at Y"
            theme_text_color: "Secondary"
            size_hint_y: None
            height: self.texture_size[1]
        MDIconButton:
            icon: 'dots-vertical'
            size_hint: None, None
            size: 24, 24
            pos_hint: {"right_x": 1}#, "center_y": .5}
            on_release: print('dots')

    MDSeparator:
        height: "1dp"
    MDFlatButton:
        text: 'print test'
        on_release: print('test')

<MyTradeTab>:
    orientation: 'vertical'
    spacing: 5
    ScrollView:
        GridLayout:
            id: box
            spacing: 5
            cols: 1
            size_hint_y: None
            height: self.minimum_height

    MDFlatButton:
        text: 'expansion'
        on_release: root.add_ep()
    MDFlatButton:
        text: 'card'
        on_release: root.add_c()

<TradeContent>:
    adaptive_height: True

    TwoLineIconListItem:
        text: "(050)-123-45-67"
        secondary_text: "Mobile"

        IconLeftWidget:
            icon: 'phone'

NavigationLayout:
    ScreenManager:
        Screen:
            BoxLayout:
                orientation: 'vertical'
                MDToolbar:
                    title: "My Best App"
                    right_action_items: [["android-messages", lambda x: drawer.set_state("toggle", animation=True)], ["dots-vertical", lambda x: app.show_theme_picker()]]

                MDBottomNavigation:
                    panel_color: app.theme_cls.accent_color

                    MDBottomNavigationItem:
                        name: 'trade'
                        text: 'Manual Trade'
                        icon: 'folder-edit'
                        MDTabs:
                            background_color: app.theme_cls.primary_color

                            MyTradeTab:
                                text: "Tab1"
                        MDFloatingActionButtonSpeedDial:
                            data:app.my_data
```

A few things:
-expansion panel is not opening unless it is not the 1st widget and you hold down the mouse
-card buttons are not doing `on_release` unless you hold down the mouse. Sometimes the ripple effect gets stuck
-Speed dial makes the bottom menu disappear
*more minor*
-Card doesn't seem to be rounded or have focus behavior
