### ISSUE TITLE
FloatingButton with custom icon

### ISSUE THREAD

**Issue by nitanmarcel** [kivymd/KivyMD#45]
How do I use a custom icon in KivyMD elements? From what I've seen the library has his own custom icon selections and I don't see a possibility to add an icon from a custom directory rather than the predefined icons given by the library.

Here is my FloatingButton kv class:

```
    FloatLayout:
        callback: lambda x: None
        FloatingButton:
            id: floating_icon
            icon: "assets/language-cpp.png" #this crashes the app
            on_release: root.manager.current = "language"
```
