### ISSUE TITLE
XXX: resource creation failed Segmentation fault (core dumped) 

### ISSUE THREAD

**Issue by icarus-0** [kivymd/KivyMD#489]
![Screenshot from 2020-08-24 13-33-52](https://user-images.githubusercontent.com/46519285/91165235-f6c58980-e6ed-11ea-9f56-e58767d8938c.png)
```python
import os
os.environ['KIVY_GL_BACKEND'] = 'gl'
#import KIVY_GL_BACKEND=gl
from kivy.metrics import dp
from kivy.clock import Clock
from kivymd.app import MDApp
from kivymd.uix.datatables import MDDataTable
from kivymd.uix.textfield import MDTextField
from kivy.uix.textinput import TextInput
from kivy.core.window import Window
import pandas as pd

class EAT(MDApp):
    r_call_data = [('3100','20.5')]
    c_call_data = [('Strike Price',dp(40)),('Price',dp(20))]

    r_put_data = [('3500','20.5')]
    c_put_data = [('Strike Price',dp(40)),('Price',dp(20))]
    i =0
    main_data = pd.read_csv(r'/home/dastaan/Eblsec_codes/strategies/01_2020_sav.csv')
    call_dict = {}
    put_dict = {}

    call_strike = 3100
    call_qty = 1
    call_strike_price = 20.5

    put_strike = 3500
    put_qty = 1
    put_strike_price = 20.5

    delta = -0.3

    Qty_lower = 1,00,000
    Qty_Upper = 2,00,000 


    def build(self):
        self.set_table()

  
    def set_table(self):
        self.data_tables_call = MDDataTable(
            pos_hint= {"center_x": .3, "center_y": .5},
            size_hint=(0.2, 0.6),
            check=True,
            column_data=self.c_call_data,
            row_data=self.r_call_data,
            
        )

        self.data_tables_put = MDDataTable(
            pos_hint= {"center_x": .7, "center_y": .5},
            size_hint=(0.2, 0.6),
            check=True,
            column_data=self.c_put_data,
            row_data=self.r_put_data,   
            
        )

        #self.data_tables_call.bind(on_row_press=self.on_row_press_call)
        self.data_tables_call.bind(on_check_press=self.on_check_press_call)

        #self.data_tables_put.bind(on_row_press=self.on_row_press_put)
        self.data_tables_put.bind(on_check_press=self.on_check_press_put)


   

    def on_start(self):
        self.data_tables_call.open()
        self.data_tables_put.open()
        Clock.schedule_interval(self.update_table,0.1)
        

    def on_check_press_call(self, instance_table, current_row):
        '''Called when the check box in the table row is checked.'''
        self.call_strike = int(current_row[0])
        self.call_strike_price = float(current_row[1])
        print(current_row)



    def on_check_press_put(self, instance_table, current_row):
        self.put_strike = int(current_row[0])
        self.put_strike_price = float(current_row[1])
        print(current_row)

    def set_delta(self):
        self.delta = (self.call_strike_price*self.call_qty - self.put_strike_price*self.put_qty ) / (self.call_strike_price*self.call_qty + self.put_strike_price*self.put_qty)
        return

    
    def update_table(self,*args):
        
        if True:
            strike_price = int(self.main_data.loc[self.i,'Strike Price'])
            opt = self.main_data.loc[self.i,'Option']
            ltp = self.main_data.loc[self.i,'Last Traded Price'] /10000
            systime = self.main_data.loc[self.i,'SYSTIME']

            if opt == 6.0:
                if strike_price in self.call_dict.keys():
                    self.call_dict[strike_price] = ltp
                else:
                    self.call_dict[strike_price] = ltp
        
            elif opt == 7.0:
                if strike_price in self.put_dict.keys():
                    self.put_dict[strike_price] = ltp
                else:
                    self.put_dict[strike_price] = ltp


            self.r_call_data = []
            self.r_put_data = []

            for k in sorted(self.call_dict.keys()):
                self.r_call_data.append(tuple ( [ str(k),str(self.call_dict[k]) ] ) )
        
            for k in sorted(self.put_dict.keys()):
                self.r_put_data.append( tuple ( [ str(k),str(self.put_dict[k]) ] ) )


            self.data_tables_put.dismiss()
            self.data_tables_call.dismiss()
            self.set_table()
            self.data_tables_call.open()
            self.data_tables_put.open()
            
            self.set_delta()

            if self.delta > -0.1 and self.delta < 0.1:
                self.root.ids.delta.text = str(round(self.delta,3))
            else:
                self.root.ids.delta.text = str(round(self.delta,3))
                #self.root.ids.delta.text_color = (1,0,0,1) 
            
            if self.delta <= -0.1:
                if opt==6.0 and self.call_strike == strike_price:
                    while self.delta< -0.1:
                        self.call_qty -= 1
                        print('headge call')
                        self.set_delta()
            
            elif self.delta >= 0.1:
                if opt==7.0 and self.put_strike == strike_price:
                    while self.delta > 0.1:
                        self.put_qty -= 1
                        print('Hedge put')
                        self.set_delta()
                
            print('Option  --> ',opt,end="  ")
            print('Strike Price -->',strike_price,end="  ")
            self.root.ids.delta.text = str(round(self.delta,3))

            if self.delta<= -0.1 or self.delta>=0.1:
                self.root.ids.delta.text_color = (1,0,0,1)
            else:
                self.root.ids.delta.text_color = (0.49,0.70,0.043,1)

            print('Delta  -->',self.delta)
            self.root.ids.call_log.text = 'Strike Price : '+str(self.call_strike)+'\nQty :    '+str(self.call_qty) 
            self.root.ids.put_log.text = 'Strike Price : '+str(self.put_strike)+'\nQty :       '+str(self.put_qty)
            self.root.ids.systime.text = str(systime)
            self.i += 1

            print(self.i)
        else:
            pass
    


EAT().run()
```

**Comment by naman-echo** [comment]
#eat.kv

```

FloatLayout:

    canvas:
        Rectangle:
            id: background
            source: '/home/dastaan/Desktop/auto_trader/back.jpg'
            size: self.size
            pos: self.pos

    BoxLayout:
        size_hint: None, None
        size: "120dp", "75dp"
        pos_hint: {"center_x":.5,"center_y":.9}
        ripple_behavior: True
        elevation: 12

        MDLabel:
            id: delta
            text: '-.3'
            theme_text_color: "Custom"
            text_color: 0.49,0.70,0.043,1
            pos_hint: {'center_x': .5, 'center_y': .5}
            font_style: 'H4'
    MDLabel:
        text: 'Delta'
        theme_text_color: "Custom"
        text_color: 0,0,0,1
        pos_hint: {'center_x': .965, 'center_y': .95}
        font_style: 'H4'

    BoxLayout:
        id: call_values
        size_hint : 0.2,1
        pos_hint: {'center_x': .3, 'center_y': .7}

    BoxLayout:
        id: put_values
        size_hint : 0.2,1
        pos_hint: {'center_x': .7, 'center_y': .7}

    
    MDLabel:
        text: 'Call Headge Details'
        pos_hint: {'center_x': .55, 'center_y': .7}
        theme_text_color: "Custom"
        text_color: 0,0,0,1
        font_style: 'H5'

    MDLabel:
        id: call_log
        text: '0'
        pos_hint: {'center_x': .55, 'center_y': .65}
        theme_text_color: "Custom"
        text_color: 1,0,0,1
        font_style: 'H6'
            
  
    MDLabel:
        text: 'Put Headge Details'
        pos_hint: {'center_x': 1.35, 'center_y': .7}
        theme_text_color: "Custom"
        text_color: 0,0,0,1
        font_style: 'H5'

    MDLabel:
        id: put_log
        text: '0'
        pos_hint: {'center_x': 1.35, 'center_y': .65}
        theme_text_color: "Custom"
        text_color: 1,0,0,1
        font_style: 'H6'



    BoxLayout:
        size: "50dp", "50dp"
        pos_hint: {'center_x': .77, 'center_y': .85}
        elevation: 12
        MDLabel:
            text: 'CALL'
            theme_text_color: "Custom"
            text_color: 0.0745098039,0.1725490196,0.431372549,1
            font_style: 'H5'

    BoxLayout:
        size: "50dp", "50dp"
        pos_hint: {'center_x': 1.17, 'center_y': .85}
        elevation: 12
        MDLabel:
            text: 'PUT'
            theme_text_color: "Custom"
            text_color: 0.0745098039,0.1725490196,0.431372549,1
            font_style: 'H5'

    MDLabel:
        id: systime
        text: '00:00:00000000'
        pos_hint: {'center_x': .55, 'center_y': .95}
        theme_text_color: "Custom"
        text_color: 1,0,0,1
        font_style: 'H5'
```
