### ISSUE TITLE
Need to be user-friendly and attractive design 

### ISSUE THREAD

**Issue by selvajack** [kivymd/KivyMD#528]
start like Facebook i mean user-friendly.to follow people easily. it good platform all these features are good but need some changes means take survey to people and company's ,Even want to simple person want to learn something it will be good platform

**Comment by HeaTTheatR** [comment]
@selvajack I do not understand what do you mean.

**Comment by podraco** [comment]
I'm not sure either, may you elaborate, please? @selvajack

**Comment by kulothunganug** [comment]
in some phones which have bigger font size kivymd looks bad

**Comment by podraco** [comment]
I would to see a screen shot

**Comment by kulothunganug** [comment]
and also in a recent git update the snackbar gets changed it looks so bad the older one is nice
pls get it back

**Comment by HeaTTheatR** [comment]
@Kulothungan16 
> and also in a recent git update the snackbar gets changed it looks so bad the older one is nice
pls get it back

Attach screenshots.

**Comment by kulothunganug** [comment]
**the old snackbar**
![git](https://user-images.githubusercontent.com/63696279/93422643-d1353580-f8d1-11ea-9f6b-9f4f39196dd7.gif)

**the new one**
![sasa](https://user-images.githubusercontent.com/63696279/93422695-f2962180-f8d1-11ea-9771-1b7c6e03f25f.png)

old has no rounded corners but the new one haves it looks bad
pls change it back

**Comment by podraco** [comment]
that's a custom property, may i see your code?

**Comment by podraco** [comment]
![image](https://user-images.githubusercontent.com/5509325/93434592-f7d17d00-f88d-11ea-8d09-797375f44efe.png)
this is with padding 0

**Comment by podraco** [comment]
This is the definiiton of the snackbar, as you can see it you set padding to 0, the round corners should dissapear
```yaml
<Snackbar>

    MDCard:
        id: box
        size_hint_y: None
        height: dp(58)
        spacing: dp(5)
        padding: dp(10)
        y: -self.height
        x: root.padding
        md_bg_color: get_color_from_hex('323232')
        radius: (5, 5, 5, 5) if root.padding else (0, 0, 0, 0) #<<--- rely on padding, when snackbar.padding is 0, the corners are sharp, otherwise, they're round.
        elevation: 11 if root.padding else 0

        MDLabel:
            id: text_bar
            size_hint_y: None
            height: self.texture_size[1]
            text: root.text
            font_size: root.font_size
            theme_text_color: 'Custom'
            text_color: get_color_from_hex('ffffff')
            shorten: True
            shorten_from: 'right'
            pos_hint: {'center_y': .5}
```
