### ISSUE TITLE
MDTextField: "Select all | Copy | Paste" bubble disappearing

### ISSUE THREAD

**Issue by akamoroz** [kivymd/KivyMD#55]
When using long tap on the MDTextField, the bubble  "Select all | Copy | Paste" appearing for less than 1 second.
There is not possible to paste something on this field.

> Android 8.1
> KivyMD 0.99.0 

Gif:
![video_2019-05-10_21-42-59](https://user-images.githubusercontent.com/985423/57549883-6d117180-736d-11e9-8050-dd62c3aa9ed2.gif)

```
<AauthForm>
    name: 'Auth Form'
    on_pre_enter: root.custom_on_pre_enter(app)

    MySpinner:
        id: update_spinner_layout

    BoxLayout:
        orientation: 'vertical'
        padding: dp(app.padding), dp(app.padding)
        spacing: dp(30)
        size_hint_y: 1
        size_hint_x: 1


        AnchorLayout:
            anchor_x: 'center'
            anchor_y: 'center'
            size_hint_y: 1
            size_hint_x: 1

            BoxLayout:
                orientation: 'vertical'
                size_hint_y: .2
                size_hint_x: .5
                spacing: 20

                BoxLayout:
                    size_hint_y: .5
                    size_hint_x: 1

                    MDTextField:
                        id: token_input
                        hint_text: app.transl_text("Enter your Token")
                        pos_hint: {'center_y': .5, 'center_x': .5}

                BoxLayout:
                    size_hint_y: .4
                    size_hint_x: .4
                    pos_hint: {'center_y': .5, 'center_x': .5}

                    MDRaisedButton:
                        id: login_button
                        text: app.transl_text('Login')
                        size_hint_x: .4
                        size_hint_y: .9
                        on_press: root.login()
```
