### ISSUE TITLE
GridLayout Error: incorret value for "orientation" in filemanager.py

### ISSUE THREAD

**Issue by DimiK1337** [kivymd/KivyMD#595]
### Description of the Bug

Kivy won't build a FileManager due to there being an invalid orientation specified for ``RecycleGridLayout`` in filemanager.py 

### Code and Logs

```python
from kivy.core.window import Window
from kivy.lang import Builder

from kivymd.app import MDApp
from kivymd.uix.filemanager import MDFileManager
from kivymd.toast import toast

kv = """
BoxLayout:
    orientation: 'vertical'

    MDToolbar:
        title: "MDFileManager"
        left_action_items: [['menu', lambda x: None]]
        elevation: 10

    FloatLayout:

        MDRoundFlatIconButton:
            text: "Open manager"
            icon: "folder"
            pos_hint: {'center_x': .5, 'center_y': .6}
            on_release: app.file_manager_open()

"""
class Example(MDApp):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        Window.bind(on_keyboard=self.events)
        self.manager_open = False
        self.file_manager = MDFileManager(
            exit_manager=self.exit_manager,
            select_path=self.select_path,
            preview=True,
        )

    def build(self):
        return Builder.load_string(KV)

    def file_manager_open(self):
        self.file_manager.show('/')  # output manager to the screen
        self.manager_open = True

    def select_path(self, path):
        '''It will be called when you click on the file name
        or the catalog selection button.

        :type path: str;
        :param path: path to the selected directory or file;
        '''

        self.exit_manager()
        toast(path)

    def exit_manager(self, *args):
        '''Called when the user reaches the root of the directory tree.'''

        self.manager_open = False
        self.file_manager.close()

    def events(self, instance, keyboard, keycode, text, modifiers):
        '''Called when buttons are pressed on the mobile device.'''

        if keyboard in (1001, 27):
            if self.manager_open:
                self.file_manager.back()
        return True

if __name__ == "__main__":
    Example().run()
```

### Error / Log output
````
File "C:\Users\dimit\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\lang\builder.py", line 712, in _apply_rule   
     e), cause=tb)
 kivy.lang.builder.BuilderException: Parser: File "<inline>", line 106:
 ...
     104:                size_hint_y: None
     105:                height: self.minimum_height
 >>  106:                orientation: "vertical"
     107:
     108:
 ...
 ValueError: RecycleGridLayout.orientation is set to an invalid option 'vertical'. Must be one of: ['lr-tb', 'tb-lr', 'rl-tb', 'tb-rl', 'lr-bt', 'bt-lr', 'rl-bt', 'bt-rl']
````

### Fix
I found a fix which was to simply remove ```orientation:'vertical'```  in kivymd/uix/filemanager.py . The section is:
```
RecycleGridLayout:
                padding: dp(10)
                cols: 3 if root.preview else 1
                default_size: None, dp(48)
                default_size_hint: 1, None
                size_hint_y: None
                height: self.minimum_height
                orientation: "vertical"
```
The fix / updated section is:
```
RecycleGridLayout:
                padding: dp(10)
                cols: 3 if root.preview else 1
                default_size: None, dp(48)
                default_size_hint: 1, None
                size_hint_y: None
                height: self.minimum_height
                #orientation: "vertical"
```

### Versions

* OS: Windows 10
* Python: 3.6.8
* Kivy: 2.0.0rc3
* KivyMD: 0.104.2.dev0
