### ISSUE TITLE
kivy app launch fails and does not return any error message

### ISSUE THREAD

**Issue by Sam-coder183** [kivymd/KivyMD#748]
### Description of the Bug

When I try to launch the app it fails and does not give any error message, this happened when I removed this lines: 

before:
**calc.py**

```
class calc(Screen):
  out = StringProperty('')
  Window.size = (420, 200)
  Window.minimum_width = 480
  Window.minimum_height = 720
```

it returned this error message:

> [WARNING] Both Window.minimum_width and Window.minimum_height must be bigger than 0 for the size restriction to take effect.

after:
```
class calc(Screen):
    out = StringProperty('')
    Window.size = (420, 200)
```
it returned nothing.

### Code and Logs

**full code:**

**calc.kv:**
```
#:kivy 1.0.9

   

<calc>:
    name: 'calc'
    BoxLayout:
        orientation: 'vertical'
        
        cols: 2
        size: root.width, root.height

        MDLabel:
            id: 'output'
            text: str(root.out)
            size_hint: 1, 0.2
            halign: 'center'

        GridLayout:
                       
            cols: 5
            MDFlatButton:
                
                text: '1'
                on_press: root.my_callback(self.text)
                
            MDFlatButton:
                
                text: '2' 
                on_press: root.my_callback(self.text)
            
            MDFlatButton:
                
                text: '3'
                on_press: root.my_callback(self.text)

            MDFlatButton:
                
                text: '-'
                on_press: root.my_callback(self.text)

            MDFlatButton:
                text: 'ac'
                on_press: root.my_callback(self.text)

            MDFlatButton:
                
                text: '4'  
                on_press: root.my_callback(self.text)

            MDFlatButton:
                
                text: '5' 
                on_press: root.my_callback(self.text)

            MDFlatButton:
                
                text: '6'
                on_press: root.my_callback(self.text)

            MDFlatButton:
                
                text: '+' 
                on_press: root.my_callback(self.text)

            MDFlatButton:
                text: '('
                on_press: root.my_callback(self.text)

            MDFlatButton:
                
                text: '7' 
                on_press: root.my_callback(self.text)

            MDFlatButton:
                
                text: '8' 
                on_press: root.my_callback(self.text)

            MDFlatButton:
                
                text: '9' 
                on_press: root.my_callback(self.text)

            MDFlatButton:
                
                text: '*'
                on_press: root.my_callback(self.text)
            
            MDFlatButton:
                text: ')'
                on_press: root.my_callback(self.text)

            MDFlatButton:
                
                text: '0' 
                on_press: root.my_callback(self.text)
            MDFlatButton:
                
                text: '.'
                on_press: root.my_callback(self.text)

            MDFlatButton:
                text: '/'
                on_press: root.my_callback(self.text)

            
            MDFlatButton:
                
                text: '**'
                on_press: root.my_callback(self.text)

            MDFlatButton:
                
                text: '='
                on_press: root.my_callback(self.text)
```

**calc.py:**

```
from logging import root
from kivymd.app import MDApp
from kivy.uix.screenmanager import Screen
from kivy.core.window import Window
from kivy.properties import StringProperty
from kivy.lang import Builder


prev = ""
expression = "" 
prox = "" 
class calc(Screen):
    out = StringProperty('')
    Window.size = (420, 200)
    Window.minimum_width = 480
    Window.minimum_height = 720
    
    
    
    def my_callback(self, inpt):
        global prev
        global expression
        global prox
        
            
        if inpt == "=":
            prox = str(eval(expression))
            self.out = prox
            expression = ""
            prev = prox
            
            
        elif inpt == "ac":
            expression = ""
            prev = ""
            prox = ""
            self.out = expression
        
        
            
        else:
            expression = prev + inpt
            prev = expression
            self.out = expression
        
         
        
                    
class calcApp(MDApp):  
    def build(self):
        def press(text):
            print("called: ", text)
    
        return calc()


if __name__ == '__main__':
    calcApp().run()
```

**main.kv:**
```
#:kivy 1.0.9
#:import calc calc.calc

NavigationLayout:
    id: nav_layout

    ScreenManager:

        Screen:

            BoxLayout:
                orientation: 'vertical'

                MDToolbar:
                    title: app.title
                    elevation: 10
                    left_action_items: [['menu', lambda x: nav_drawer.set_state()]]

                ScreenManager:
                    id: screen_manager
                    calculator:
                        
                    

    MDNavigationDrawer:
        id: nav_drawer

        BoxLayout:
            orientation: 'vertical'
            padding: '8dp'
            spacing: '8dp'

            Image:
                size_hint: None, None
                size: '280dp', "200dp"
                source: "logo.png"
            
            ScrollView:
            
                MDList:

                    OneLineIconListItem:
                        text: "calculadora"
                        on_release:
                            screen_manager.add_widget(calc())
                            screen_manager.current = 'calc'
                            nav_drawer.set_state()
                        IconLeftWidget:
                            icon: 'view-dashboard'
```
**main.py:**
```
import calc
from kivymd.app import MDApp
from kivy.lang import Builder
from kivy.uix.screenmanager import Screen, ScreenManager

Builder.load_file("calc.kv")

class MyApp(MDApp):
    def build(self):
        self.title = "calculadora"
        self.theme_cls.primary_palette = "Green"
        return Builder.load_file("main.kv")
```
**log after removing the lines: ** 
```
[INFO   ] [Logger      ] Record log in C:\Users\samuel\.kivy\logs\kivy_21-01-02_20.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.2.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.2.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.2.0
[INFO   ] [Kivy        ] v2.0.0rc3, git-20c14b2, 20200615
[INFO   ] [Kivy        ] Installed at "C:\Python38\lib\site-packages\kivy\__init__.py"  
[INFO   ] [Python      ] v3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Python38\python.exe"
[INFO   ] [KivyMD      ] v0.104.1
[INFO   ] [Factory     ] 185 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer, img_gif ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.14757 Compatibility Profile Context 20.12.1 27.20.14501.28009'>
[INFO   ] [GL          ] OpenGL vendor <b'ATI Technologies Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'Radeon RX 580 Series'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [GL          ] NPOT texture support is available
 ```

### Versions

* OS: Windows 10 Pro 20H2
* Python: python 3.8.2 64bit
* Kivy: 2.0.0rc3
* KivyMD: 0.104.1
