### ISSUE TITLE
Can't add Image on top of a list in KivyMD

### ISSUE THREAD

**Issue by Luck24** [kivymd/KivyMD#881]
### Description of the Bug

I am trying to make an app that will display facts in a list, and on the top of the list, I want an image. So I add the image to the MDList that is in a ScrollLayout in code, but it doesn't work, btw adding a switch or label on top with the same code works!

### Versions

* OS:  Windows 10-64bit
* Python: 3.7.6
* Kivy: 2.0.0
* KivyMD: 0.104.1

**Comment by HeaTTheatR** [comment]
@Luck24 Please describe your question in one message, `attach a minimal code` that may be run `without additional manipulations`, so developers can look at the working script and fix it. Also write what you expect from the script and what happened wrong. If needed, attach links or screenshots to explain us what you want to do.

**Comment by Luck24** [comment]
**FROM PYTHON SCRIPT**
`self.root.ids.sorted_list.add_widget(Image(source="myimage.png"))`

**IN KV FILE:**
```
Screen:
                name: "scr_sort_list"

                ScrollView:
                    pos_hint: {"top": .92}
                    size_hint: (1, .92)
                    MDList:
                        id: sorted_list
```
