### ISSUE TITLE
MDNavigationLayout in example on github

### ISSUE THREAD

**Issue by skorpions2000** [kivymd/KivyMD#906]
Replace please in:
https://github.com/kivymd/KivyMD/wiki/Components-Navigation-Drawer
```
Screen:

    NavigationLayout:

        ScreenManager:

            Screen:

                BoxLayout:
                    orientation: 'vertical'

                    MDToolbar:
                        title: "Navigation Drawer"
                        elevation: 10
                        left_action_items: [['menu', lambda x: nav_drawer.toggle_nav_drawer()]]

                    Widget:


        MDNavigationDrawer:
            id: nav_drawer

            ContentNavigationDrawer:
                id: content_drawer
```
NavigationLayout to MDNavigationLayout
nav_drawer.toggle_nav_drawer() to nav_drawer.set_state()

Because don't work example with pip install https://github.com/kivymd/KivyMD/archive/master.zip

and don't work with build-in buildozer apk, with requirements = kivy==2.0.0, kivymd==0.104.1
send org.test.myapp I/python:  kivy.factory.FactoryException: Unknown class <NavigationLayout> 
i do not why in IDE this combination is working =(

If chose archive master from GitHub and replace code like top, all is work in both.
