### ISSUE TITLE
Custom button background color in dialog boxes doesn't work on IOS

### ISSUE THREAD

**Issue by orlandoalexander** [kivymd/KivyMD#949]
### Description of the Bug

I have been using the md_bg_color property for an MDRaisedButton in a dialog box to give a custom color background for the button. This works absolutely fine on desktop, but when I run it on IOS, the background color defaults to light blue.

### Code and Logs
Python
```
from kivy.app import App
from kivymd.app import MDApp
from kivymd.uix.button import MDFlatButton, MDRaisedButton


class UserLocation_Content(BoxLayout):
    pass

class MyClass(Screen):
    def MyMethod(self, MDApp):
        self.dialog = MDDialog(
                    title="Enter your address:",
                    auto_dismiss=False,
                    type="custom",
                    content_cls=UserLocation_Content(),  # content class
                    buttons=[MDFlatButton(text="CANCEL", text_color=((128 / 255), (128 / 255), (128 / 255), 1)), MDRaisedButton(text="CONFIRM", opacity = 1, text_color=(0,0,0,1), md_bg_color = [11/255,156/255,49/255,1], on_press = self.check_postcode)])
        self.dialog.open()
```

KV
```
<UserLocation_Content>:
    orientation: "vertical"
    spacing: "12dp"
    size_hint_y: None
    height: "50dp"

    MDTextField:
        hint_text: "Postcode"
        color_mode: 'custom'
        line_color_normal: ((62 / 255), (155 / 255), (239 / 255), 1)
        line_color_focus: [11/255,156/255,49/255,1]
```

### Screenshots

Desktop: 

![Screenshot 2021-04-07 at 12 55 18 pm](https://user-images.githubusercontent.com/67097862/113863435-92010000-97a1-11eb-949e-b3c618395e64.png)

IOS: 

![IMG_2880](https://user-images.githubusercontent.com/67097862/113863471-9cbb9500-97a1-11eb-9e95-406990dcddfd.PNG)

### Versions

* macOS: 11.2.3
* IOS: 14.4.2
* Python: 3.8
* Kivy: 2.0.0
* KivyMD: 0.104.2.dev0
